import type { PassElementsRegister } from 'proton-pass-extension/app/content/elements';

import '@proton/pass/globals.d';
import type { Maybe } from '@proton/pass/types';

export type ExportFunction = <Fn extends Function>(fn: Fn, target: any, options: { defineAs: string }) => void;
export type CloneInto = <T>(obj: T, target: any, options: { cloneFunctions?: boolean; wrapReflectors?: boolean }) => T;

declare global {
    interface Window {
        /** This function is injected via a page-script in the main world
         * via the InjectionService. `hash` is a unique identifier per tab
         * and per service worker generated by the service worker.  */
        registerPassElements?: PassElementsRegister;
        wrappedJSObject?: Window;
    }

    var cloneInto: Maybe<CloneInto>;
    var exportFunction: Maybe<ExportFunction>;

    declare const HTTP_DEBUGGER_PORT: number;
    declare const HTTP_DEBUGGER: boolean;
}
