import type { Attachment, ContentBlock, Message } from '../types';
import { countTokens } from './tokenizer';

/**
 * Calculate token count for a single content block.
 * Delegates to appropriate calculation based on block type.
 */
function calculateBlockTokens(block: ContentBlock): number {
    switch (block.type) {
        case 'text':
            return countTokens(block.content);
        case 'tool_call':
            return countTokens(block.content);
        case 'tool_result':
            return countTokens(block.content);
        default:
            // Future-proof: unknown block types
            return 0;
    }
}

/**
 * Calculate tokens from message content only (excluding context)
 * Used for UI components that need to show message content tokens separately
 */
function isToolContentBlock(block: ContentBlock): boolean {
    return block.type === 'tool_call' || block.type === 'tool_result';
}

export type MessageTokenBreakdown = {
    /** User/assistant text blocks (excludes tool_call and tool_result). */
    textTokens: number;
    /** tool_call and tool_result blocks. */
    toolTokens: number;
};

export function calculateMessageTokenBreakdown(messageChain: Message[]): MessageTokenBreakdown {
    return messageChain.reduce<MessageTokenBreakdown>(
        (acc, message) => {
            if (message.blocks && message.blocks.length > 0) {
                for (const block of message.blocks) {
                    const tokens = calculateBlockTokens(block);
                    if (isToolContentBlock(block)) {
                        acc.toolTokens += tokens;
                    } else {
                        acc.textTokens += tokens;
                    }
                }
            } else {
                acc.textTokens += countTokens(message.content);
                acc.toolTokens += countTokens(message.toolCall) + countTokens(message.toolResult);
            }
            return acc;
        },
        { textTokens: 0, toolTokens: 0 }
    );
}

export const calculateMessageContentTokens = (messageChain: Message[]): number => {
    const { textTokens, toolTokens } = calculateMessageTokenBreakdown(messageChain);
    return textTokens + toolTokens;
};

// Calculate estimated tokn size for a single attachment
export const countAttachmentTokenVersion = 1;
export const countAttachmentToken = (attachment: Attachment): number => {
    if (!attachment || attachment.processing || !attachment.filename) {
        return 0;
    }

    // IMPORTANT: If we change the logic here,
    // we need to bump countAttachmentTokenVersion!

    // Prefer the cached token count. This must come before the markdown check:
    // historical/shallow attachments keep `tokenCount` but have their `markdown`
    // stripped (it lives in IndexedDB), so guarding on markdown first would make
    // them report 0 and disappear from context-size estimates.
    if (attachment.tokenCount !== undefined && attachment.tokenCount > 0) {
        return attachment.tokenCount;
    }

    // Without cached tokens we need the markdown content to estimate.
    if (!attachment.markdown) {
        return 0;
    }

    try {
        // Calculate the context that would be generated by flattenAttachmentsForLlm for this file
        const filename = `Filename: ${attachment.filename}`;
        const header = 'File contents:';
        const beginMarker = '----- BEGIN FILE CONTENTS -----';
        const endMarker = '----- END FILE CONTENTS -----';
        const content = attachment.markdown.trim();

        const fullContext = [filename, header, beginMarker, content, endMarker].join('\n');

        // Use fast approximation for better performance (4 chars/token)
        return countTokens(fullContext);
    } catch (error) {
        console.warn('Error calculating attachment context size:', error, attachment);
        return 0;
    }
};

/**
 * Calculate estimated token size for attachments based on their markdown content.
 * This function simulates the token cost of what would be sent to the LLM.
 *
 * @param attachments Array of attachments to calculate context size for
 * @returns Total estimated token count for all attachments
 */
export const calculateAttachmentContextSize = (attachments: Attachment[]): number => {
    return attachments.reduce((total, attachment) => {
        return total + countAttachmentToken(attachment);
    }, 0);
};

export const formatTokenCount = (tokenCount: number): string => {
    if (tokenCount < 1000) {
        return `${Math.round(tokenCount)} tokens`;
    } else {
        return `${(tokenCount / 1000).toFixed(1)}K tokens`;
    }
};

// Get size level for individual files
export const getFileSizeLevel = (tokenCount: number): 'small' | 'medium' | 'large' | 'very-large' => {
    if (tokenCount >= 20000) {
        // Very large single file
        return 'very-large';
    } else if (tokenCount >= 10000) {
        // Large single file
        return 'large';
    } else if (tokenCount >= 5000) {
        // Medium single file
        return 'medium';
    }
    return 'small';
};

// Get progress bar state for visual indicators
export const getContextProgressState = (percentage: number): 'low' | 'medium' | 'high' | 'critical' => {
    if (percentage >= 100) {
        return 'critical';
    } else if (percentage >= 75) {
        return 'high';
    } else if (percentage >= 50) {
        return 'medium';
    }
    return 'low';
};

