export const UNIQUE = 1;

export const PROPERTIES = {
    id: UNIQUE,
    uid: UNIQUE,
    dtstamp: UNIQUE,
    class: UNIQUE,
    created: UNIQUE,
    description: UNIQUE,
    geo: UNIQUE,
    'last-modified': UNIQUE,
    'recurrence-id': UNIQUE,
    location: UNIQUE,
    organizer: UNIQUE,
    priority: UNIQUE,
    sequence: UNIQUE,
    status: UNIQUE,
    summary: UNIQUE,
    transp: UNIQUE,
    trigger: UNIQUE,
    action: UNIQUE,
    url: UNIQUE,
    rrule: UNIQUE,
    dtstart: UNIQUE,
    dtend: UNIQUE,
    duration: UNIQUE,
    repeat: UNIQUE,
    attach: UNIQUE,
    due: UNIQUE,
    tzid: UNIQUE,
    prodid: UNIQUE,
    'x-wr-calname': UNIQUE,
    'x-wr-timezone': UNIQUE,
    version: UNIQUE,
    calscale: UNIQUE,
    method: UNIQUE,
};
