import type { NewsletterSubscription } from '@proton/shared/lib/interfaces/NewsletterSubscription';

export const smallFakeSubscriptions: NewsletterSubscription[] = [
    {
        ID: '1',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'no-reply@dropbox.com',
        BimiSelector: 'selector',
        Name: 'Dropbox',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 10,
        UnreadMessageCount: 13,
        TrackersCount: 24,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '2',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'marketing-no-reply@linkedin.com',
        BimiSelector: 'selector',
        Name: 'LinkedIn',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 12,
        UnreadMessageCount: 4,
        TrackersCount: 7,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '3',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'notifications-no-reply@linkedin.com',
        BimiSelector: 'selector',
        Name: 'LinkedIn',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 20,
        UnreadMessageCount: 13,
        TrackersCount: 56,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '4',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'noreply@reddit.com',
        BimiSelector: 'selector',
        Name: 'Reddit',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 9,
        UnreadMessageCount: 2,
        TrackersCount: 34,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '5',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'news-marketing@amazon.com',
        BimiSelector: 'selector',
        Name: 'Amazon',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
];

export const fakeSubscriptions: NewsletterSubscription[] = [
    {
        ID: '1',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'no-reply@dropbox.com',
        BimiSelector: 'selector',
        Name: 'Dropbox',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 10,
        UnreadMessageCount: 13,
        TrackersCount: 24,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '2',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'marketing-no-reply@linkedin.com',
        BimiSelector: 'selector',
        Name: 'LinkedIn',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 12,
        UnreadMessageCount: 4,
        TrackersCount: 7,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '3',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'notifications-no-reply@linkedin.com',
        BimiSelector: 'selector',
        Name: 'LinkedIn',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 20,
        UnreadMessageCount: 13,
        TrackersCount: 56,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '4',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'noreply@reddit.com',
        BimiSelector: 'selector',
        Name: 'Reddit',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 9,
        UnreadMessageCount: 2,
        TrackersCount: 34,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '5',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'news-marketing@amazon.com',
        BimiSelector: 'selector',
        Name: 'Amazon',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '6',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'news@washingtonpost.com',
        BimiSelector: 'selector',
        Name: 'Washington Post',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '7',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'course@tailwindcss.com',
        BimiSelector: 'selector',
        Name: 'Adam Wathan',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '8',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'dan@tldrnewsletter.com',
        BimiSelector: 'selector',
        Name: 'TLDR Web Dev',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '9',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'sebastien@thisweekinreact.com',
        BimiSelector: 'selector',
        Name: 'This Week In React',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '10',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'superlongemailaddress@superlongdomain.com',
        BimiSelector: 'selector',
        Name: 'This is a super long text to see how things behave',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 8,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '11',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'superlongemailaddress@superlongdomain.com',
        BimiSelector: 'selector',
        Name: '0 trackers',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 0,
        TrackersCount: 22,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '12',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'superlongemailaddress@superlongdomain.com',
        BimiSelector: 'selector',
        Name: 'No trackers',
        UnsubscribedTime: 0,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 0,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
    {
        ID: '13',
        UserId: '1',
        AddressId: '1',
        SenderAddress: 'unsubscribed@test.com ',
        BimiSelector: 'selector',
        Name: 'Testing',
        UnsubscribedTime: 10,
        FirstReceivedTime: '2022-01-01T00:00:00Z',
        LastReceivedTime: '2022-01-01T00:00:00Z',
        LastReadTime: '2022-01-01T00:00:00Z',
        ReceivedMessageCount: 23,
        UnreadMessageCount: 0,
        ListId: '1',
        MarkAsRead: false,
        MoveToFolder: '',
    },
];
