fastTrack:
    allowList:
        - msvanstr
        - jcrompton
        - rtetaz
        - mhorejsek
        - zpetresk
        - ecandon
        - akarpov
        - lpeslier
        - nhoffmann
        - rrychets
        - rsanchez
        - ggonzalez
        - fbonvin
        - djankovic
        - aharwara
        - pchiabre
forbiddenTags:
    - state::Blocked
ciFailFast: true
