fastTrack:
    allowList:
        - msvanstr
        - jcrompton
        - rtetaz
        - mhorejsek
        - zpetresk
        - ecandon
        - akarpov
        - lpeslier
        - pbondoer
        - nhoffmann
        - rrychets
        - rsanchez
        - ggonzalez
        - fbonvin
        - seraph
        - djankovic
        - glinford
        - hbutt
        - mbitar
        - aharwara
forbiddenTags:
    - state::Blocked
ciFailFast: true
