httpProxy: '${http_proxy:-}'

httpsProxy: '${https_proxy:-}'

nodeLinker: node-modules

plugins:
    - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.9.4.cjs

npmPublishRegistry: https://nexus.protontech.ch/repository/web-npm/

npmScopes:
    tpe:
        npmRegistryServer: 'https://gitlab.protontech.ch/api/v4/projects/4357/packages/npm/'
        npmAuthToken: '${CI_JOB_TOKEN:-}'
    proton-meet:
        npmRegistryServer: 'https://nexus.protontech.ch/repository/meet-npm/'

npmAuditIgnoreAdvisories:
    # Ignore advisories for xlsx package. This package is depended on by a third-party library rowsncolumns (docs)
    # and hasn't gotten any priority to change.
    - 1108110
    - 1108111
