approvedGitRepositories:
    - '**'

compressionLevel: mixed

enableConstraintsChecks: true

enableScripts: true

httpProxy: '${http_proxy:-}'

httpsProxy: '${https_proxy:-}'

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
    - 1108110
    - 1108111

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
    - '@proton/*'
    - '@proton-meet/*'
    - '@protontech/*'
    - '@openpgp/*'
    - '@tpe/*'

npmPublishRegistry: 'https://nexus.protontech.ch/repository/web-npm/'

npmScopes:
    proton:
        npmRegistryServer: 'https://nexus.protontech.ch/repository/foundation-npm/'
    proton-meet:
        npmRegistryServer: 'https://nexus.protontech.ch/repository/meet-npm/'
    tpe:
        npmAuthToken: '${CI_JOB_TOKEN:-}'
        npmRegistryServer: 'https://gitlab.protontech.ch/api/v4/projects/4357/packages/npm/'

plugins:
    - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.14.1.cjs
