httpProxy: '${http_proxy:-}'

httpsProxy: '${https_proxy:-}'

nodeLinker: node-modules

plugins:
    - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.9.2.cjs

npmPublishRegistry: https://nexus.protontech.ch/repository/web-npm/

# Needed for Drive SDK. Will be gone once it is in public npm registry.
npmScopes:
    proton:
        npmRegistryServer: https://nexus.protontech.ch/repository/drive-npm/
