httpProxy: '${http_proxy:-}'

httpsProxy: '${https_proxy:-}'

nodeLinker: node-modules

plugins:
    - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.9.0.cjs

npmPublishRegistry: https://nexus.protontech.ch/repository/web-npm/
