const animalNames = [
    'Lion',
    'Tiger',
    'Elephant',
    'Giraffe',
    'Zebra',
    'Kangaroo',
    'Panda',
    'Koala',
    'Penguin',
    'Dolphin',
    'Eagle',
    'Butterfly',
    'Dove',
    'Horse',
    'Rabbit',
    'Deer',
    'Fox',
    'Otter',
    'Bear',
    'Falcon',
    'Parrot',
    'Bee',
    'Ladybug',
    'Goldfish',
    'Peacock',
    'Dragonfly',
    'Seal',
    'Whale',
    'Wolf',
    'Swan',
    'Robin',
    'Finch',
    'Canary',
    'Gazelle',
    'Moose',
    'Buffalo',
    'Camel',
    'Sheep',
    'Goat',
    'Turtle',
    'Tortoise',
    'Frog',
    'Hummingbird',
    'Bluebird',
    'Jay',
    'Cardinal',
    'Wren',
    'Puffin',
    'Caribou',
    'Bison',
    'Leopard',
];

export const getRandomParticipantName = () => {
    const randomIndex = Math.floor(Math.random() * animalNames.length);

    return `Anonymous ${animalNames[randomIndex]} ${Math.floor(Math.random() * 1000)}`;
};
