#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const _ = require('lodash');

const isDebug = process.argv.includes('--debug');

try {

    const doc = fs.readFileSync(path.resolve('./po/template.pot'));
    const translations = _.filter(doc.toString().split(/^\s*\n/gm), (str) => {
        return !str.includes('msgctxt') && !str.includes('Project-Id-Version');
    });
    const total = translations.length;
    const verb = (total > 1) ? 'are' : 'is';

    if (!isDebug && total) {
        throw new Error(`There ${verb} ${total} translation(s) without context !`);
    }

    if (isDebug && total) {
        console.log(translations.sort().join('\n'));
        process.exit(1);
    }

    process.exit(0);
} catch (e) {
    console.error(e.message);
    process.exit(1);
}
