export const App_TYPES = {
  // Services
  DocsApi: Symbol.for('DocsApi'),
  HttpService: Symbol.for('HttpService'),
  DocLoader: Symbol.for('DocOrchestrator'),
  Logger: Symbol.for('Logger'),
  EventBus: Symbol.for('EventBus'),
  WebsocketService: Symbol.for('WebsocketService'),
  RealtimeEncryptionService: Symbol.for('RealtimeEncryptionService'),
  CommentsEncryptionService: Symbol.for('CommentsEncryptionService'),
  MetricService: Symbol.for('MetricService'),

  // Use cases
  SquashDocument: Symbol.for('SquashDocument'),
  CreateInitialCommit: Symbol.for('CreateInitialCommit'),
  EncryptMessage: Symbol.for('EncryptMessage'),
  DecryptMessage: Symbol.for('DecryptMessage'),
  CreateDocument: Symbol.for('CreateDocument'),
  GetDocumentMeta: Symbol.for('GetDocumentMeta'),
  EncryptComment: Symbol.for('EncryptComment'),
  DecryptComment: Symbol.for('DecryptComment'),
  DuplicateDocument: Symbol.for('DuplicateDocument'),
  CreateNewDocument: Symbol.for('CreateNewDocument'),
  CreateEmptyDocumentForConversion: Symbol.for('CreateEmptyDocumentForConversion'),
  CreateRealtimeValetToken: Symbol.for('CreateRealtimeValetToken'),
  LoadDocument: Symbol.for('LoadDocument'),
  LoadCommit: Symbol.for('LoadCommit'),
  GetCommitData: Symbol.for('GetCommitData'),
  DecryptCommit: Symbol.for('DecryptCommit'),
  VerifyCommit: Symbol.for('VerifyCommit'),
  VerifyMessages: Symbol.for('VerifyMessages'),
  SquashAlgorithm: Symbol.for('SquashAlgorithm'),
  CreateComment: Symbol.for('CreateComment'),
  CreateThread: Symbol.for('CreateThread'),
  LoadThreads: Symbol.for('LoadThreads'),
  HandleRealtimeCommentsEvent: Symbol.for('HandleRealtimeCommentsEvent'),
  ExportAndDownload: Symbol.for('ExportAndDownload'),
}
