/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SelectorV1 = string;

export interface DetectionRulesV1 {
    /**
     * rules version to know the structure to parse at runtime
     */
    version: '1';
    rules: {
        /**
         * @minItems 0
         *
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^(\w+)(\.(\w+))*(/\w+)*$".
         */
        [k: string]: SelectorV1[];
    };
}
