import { c } from 'ttag';

import { ModalOwnProps } from '@proton/components/components';
import walletSeedphraseSrc from '@proton/styles/assets/img/illustrations/wallet-access-key.svg';
import walletPassphraseSrc from '@proton/styles/assets/img/illustrations/wallet-passphrase.svg';

import { Modal } from '../../atoms';

type ContentKind = 'wallet-seedphrase-introduction' | 'wallet-passphrase-introduction';

const getContent = (kind: ContentKind) => {
    const content: Record<ContentKind, { title: string; image: string; text: string }> = {
        ['wallet-seedphrase-introduction']: {
            title: c('Wallet information').t`What’s a wallet seed phrase?`,
            image: walletSeedphraseSrc,
            text: c('Wallet information')
                .t`A wallet seed phrase is a series of 12 or 24 words generated by your wallet. It acts as a master key, allowing you to recover your funds. Keep it safe and never share it, as it grants access to your funds.`,
        },
        ['wallet-passphrase-introduction']: {
            title: c('Wallet information').t`What’s a wallet passphrase?`,
            image: walletPassphraseSrc,
            text: c('Wallet information')
                .t`A wallet passphrase is an extra password you create to add security to your cryptocurrency wallet. It works alongside your seed phrase. Store it securely, as losing it can lock you out of your wallet.`,
        },
    };

    return content[kind];
};

export interface WalletInformationalModalOwnProps {
    kind: ContentKind;
}

export const WalletInformationalModal = ({ kind, ...modalProps }: WalletInformationalModalOwnProps & ModalOwnProps) => {
    const { title, image, text } = getContent(kind);

    return (
        <Modal size="small" {...modalProps}>
            <div className="flex flex-column items-center">
                <img src={image} alt="" className="mb-6" />

                <h1 className="my-4 text-semibold text-3xl">{title ?? c('Wallet Upgrade').t`Upgrade your privacy`}</h1>

                <p className="mt-0 mb-8 color-hint text-center">{text}</p>
            </div>
        </Modal>
    );
};
