/* @ts-self-types="./index.d.ts" */
import * as wasm from "./index_bg.wasm";
import { __wbg_set_wasm } from "./index_bg.js";

__wbg_set_wasm(wasm);
wasm.__wbindgen_start();
export {
    WasmAccount, WasmAccountStatementGenerator, WasmAccountSweeper, WasmAccountSyncer, WasmAddress, WasmAddressDetailsArray, WasmAddressDetailsData, WasmAddressInfo, WasmApiBitcoinAddressCreationPayloadData, WasmApiBitcoinAddressesCreationPayload, WasmApiClients, WasmApiExchangeRateData, WasmApiFiatCurrencies, WasmApiFiatCurrencyData, WasmApiWalletAccountAddresses, WasmApiWalletAccounts, WasmApiWalletBitcoinAddressData, WasmApiWalletBitcoinAddressIndexes, WasmApiWalletBitcoinAddressLookupData, WasmApiWalletBitcoinAddressUsedIndexData, WasmApiWalletBitcoinAddresses, WasmApiWalletData, WasmApiWalletTransactionData, WasmApiWalletTransactions, WasmApiWalletsData, WasmAuthData, WasmBalanceWrapper, WasmBitcoinAddressClient, WasmBlockchainClient, WasmChangeSpendPolicy, WasmCoinSelection, WasmCountriesAndProviderTupple, WasmCountriesByProvider, WasmDerivationPath, WasmDetailledTxIn, WasmDiscoveredAccount, WasmDiscoveredAccounts, WasmEmailIntegrationClient, WasmExchangeRateClient, WasmFiatCurrenciesAndProviderTupple, WasmFiatCurrenciesByProvider, WasmInviteClient, WasmKeychainKind, WasmLanguage, WasmLockTime, WasmMessageSigner, WasmMigratedWalletAccountData, WasmMigratedWalletAccounts, WasmMigratedWalletTransactionData, WasmMigratedWalletTransactions, WasmMinimumFees, WasmMnemonic, WasmNetwork, WasmNetworkClient, WasmOnchainPaymentLink, WasmOutPoint, WasmPaperAccount, WasmPaymentGatewayClient, WasmPaymentLink, WasmPaymentLinkKind, WasmPaymentMethodsAndProviderTupple, WasmPaymentMethodsByProvider, WasmPriceGraphClient, WasmProtonWalletApiClient, WasmPsbt, WasmPsbtAndTxBuilder, WasmPsbtRecipient, WasmQuotesAndProviderTupple, WasmQuotesByProvider, WasmRecipient, WasmRecommendedFees, WasmRemainingMonthlyInvitations, WasmScript, WasmScriptType, WasmSequence, WasmSettingsClient, WasmSigningType, WasmSortOrder, WasmTransaction, WasmTransactionDetailsArray, WasmTransactionDetailsData, WasmTransactionFilter, WasmTxBuilder, WasmTxOut, WasmUserSettingsData, WasmUtxo, WasmUtxoArray, WasmWallet, WasmWalletAccountAddressData, WasmWalletAccountData, WasmWalletClient, WasmWalletTransactionFlag, WasmWordCount, WasmWrappedPriceGraph, createTransactionFromPsbt, getDefaultStopGap, getWordsAutocomplete, setPanicHook
} from "./index_bg.js";
