export const JOIN_TITLE_TIMEOUT = 2000;

export const NOTIFICATION_PARTICIPANT_LIMIT = 10;

export const DEFAULT_DEVICE_ID = 'default';

export const MEETING_LOCKED_ERROR_CODE = 2502;

export const PIP_PREVIEW_ITEM_WIDTH = 480;
export const PIP_PREVIEW_ITEM_HEIGHT = 270;

export const JOIN_SOUND_NOTIFICATION_PARTICIPANT_LIMIT = 5;

export const REACTION_DISPLAY_DURATION_MS = 3_000;

export const RAISE_HAND_EMOJI = '✋';
