/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter eslint_disable
// @generated from protobuf file "action-payload-v1.proto" (package "proton_pass_action_payload_v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';

/**
 * @generated from protobuf message proton_pass_action_payload_v1.AgentAction
 */
export interface AgentAction {
    /**
     * @generated from protobuf field: string reason = 1
     */
    reason: string;
    /**
     * @generated from protobuf field: string vault_name = 2
     */
    vaultName: string;
    /**
     * @generated from protobuf field: string item_name = 3
     */
    itemName: string;
    /**
     * @generated from protobuf field: string folder_name = 4
     */
    folderName: string;
}
/**
 * @generated from protobuf message proton_pass_action_payload_v1.ActionPayload
 */
export interface ActionPayload {
    /**
     * @generated from protobuf oneof: content
     */
    content:
        | {
              oneofKind: 'agentAction';
              /**
               * @generated from protobuf field: proton_pass_action_payload_v1.AgentAction agent_action = 1
               */
              agentAction: AgentAction;
          }
        | {
              oneofKind: undefined;
          };
}
// @generated message type with reflection information, may provide speed optimized methods
class AgentAction$Type extends MessageType<AgentAction> {
    constructor() {
        super('proton_pass_action_payload_v1.AgentAction', [
            { no: 1, name: 'reason', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: 'vault_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: 'item_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: 'folder_name', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
        ]);
    }
    create(value?: PartialMessage<AgentAction>): AgentAction {
        const message = globalThis.Object.create(this.messagePrototype!);
        message.reason = '';
        message.vaultName = '';
        message.itemName = '';
        message.folderName = '';
        if (value !== undefined) reflectionMergePartial<AgentAction>(this, message, value);
        return message;
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: AgentAction
    ): AgentAction {
        let message = target ?? this.create(),
            end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string reason */ 1:
                    message.reason = reader.string();
                    break;
                case /* string vault_name */ 2:
                    message.vaultName = reader.string();
                    break;
                case /* string item_name */ 3:
                    message.itemName = reader.string();
                    break;
                case /* string folder_name */ 4:
                    message.folderName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        );
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgentAction, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string reason = 1; */
        if (message.reason !== '') writer.tag(1, WireType.LengthDelimited).string(message.reason);
        /* string vault_name = 2; */
        if (message.vaultName !== '') writer.tag(2, WireType.LengthDelimited).string(message.vaultName);
        /* string item_name = 3; */
        if (message.itemName !== '') writer.tag(3, WireType.LengthDelimited).string(message.itemName);
        /* string folder_name = 4; */
        if (message.folderName !== '') writer.tag(4, WireType.LengthDelimited).string(message.folderName);
        let u = options.writeUnknownFields;
        if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proton_pass_action_payload_v1.AgentAction
 */
export const AgentAction = new AgentAction$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActionPayload$Type extends MessageType<ActionPayload> {
    constructor() {
        super('proton_pass_action_payload_v1.ActionPayload', [
            { no: 1, name: 'agent_action', kind: 'message', oneof: 'content', T: () => AgentAction },
        ]);
    }
    create(value?: PartialMessage<ActionPayload>): ActionPayload {
        const message = globalThis.Object.create(this.messagePrototype!);
        message.content = { oneofKind: undefined };
        if (value !== undefined) reflectionMergePartial<ActionPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: ActionPayload
    ): ActionPayload {
        let message = target ?? this.create(),
            end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* proton_pass_action_payload_v1.AgentAction agent_action */ 1:
                    message.content = {
                        oneofKind: 'agentAction',
                        agentAction: AgentAction.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options,
                            (message.content as any).agentAction
                        ),
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        );
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActionPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* proton_pass_action_payload_v1.AgentAction agent_action = 1; */
        if (message.content.oneofKind === 'agentAction')
            AgentAction.internalBinaryWrite(
                message.content.agentAction,
                writer.tag(1, WireType.LengthDelimited).fork(),
                options
            ).join();
        let u = options.writeUnknownFields;
        if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proton_pass_action_payload_v1.ActionPayload
 */
export const ActionPayload = new ActionPayload$Type();
