/* eslint-disable */
// @generated by hand to mirror protoc-gen-ts output for action-payload-v1.proto
// (this avoids running yarn generate:proto for a single new message; can be
// regenerated from the .proto file using the standard pipeline if needed).
// tslint:disable
import { MessageType, UnknownFieldHandler, WireType, reflectionMergePartial } from '@protobuf-ts/runtime';
import type {
    BinaryReadOptions,
    BinaryWriteOptions,
    IBinaryReader,
    IBinaryWriter,
    PartialMessage,
} from '@protobuf-ts/runtime';

/**
 * @generated from protobuf message proton_pass_action_payload_v1.AgentAccessItem
 */
export interface AgentAccessItem {
    /**
     * @generated from protobuf field: string reason = 1
     */
    reason: string;
    /**
     * @generated from protobuf field: string vault_name = 2
     */
    vaultName: string;
    /**
     * @generated from protobuf field: string item_name = 3
     */
    itemName: string;
}

/**
 * @generated from protobuf message proton_pass_action_payload_v1.ActionPayload
 */
export interface ActionPayload {
    /**
     * @generated from protobuf oneof: content
     */
    content: { oneofKind: 'agentAccessItem'; agentAccessItem: AgentAccessItem } | { oneofKind: undefined };
}

class AgentAccessItem$Type extends MessageType<AgentAccessItem> {
    constructor() {
        super('proton_pass_action_payload_v1.AgentAccessItem', [
            { no: 1, name: 'reason', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: 'vault_name', kind: 'scalar', jsonName: 'vaultName', T: 9 },
            { no: 3, name: 'item_name', kind: 'scalar', jsonName: 'itemName', T: 9 },
        ]);
    }
    create(value?: PartialMessage<AgentAccessItem>): AgentAccessItem {
        const message = globalThis.Object.create(this.messagePrototype!);
        message.reason = '';
        message.vaultName = '';
        message.itemName = '';
        if (value !== undefined) reflectionMergePartial<AgentAccessItem>(this, message, value);
        return message;
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: AgentAccessItem
    ): AgentAccessItem {
        let message = target ?? this.create();
        const end = reader.pos + length;
        while (reader.pos < end) {
            const [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    message.reason = reader.string();
                    break;
                case 2:
                    message.vaultName = reader.string();
                    break;
                case 3:
                    message.itemName = reader.string();
                    break;
                default:
                    const u = options.readUnknownField;
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        );
                    const d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgentAccessItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        if (message.reason !== '') writer.tag(1, WireType.LengthDelimited).string(message.reason);
        if (message.vaultName !== '') writer.tag(2, WireType.LengthDelimited).string(message.vaultName);
        if (message.itemName !== '') writer.tag(3, WireType.LengthDelimited).string(message.itemName);
        const u = options.writeUnknownFields;
        if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
export const AgentAccessItem = new AgentAccessItem$Type();

class ActionPayload$Type extends MessageType<ActionPayload> {
    constructor() {
        super('proton_pass_action_payload_v1.ActionPayload', [
            {
                no: 1,
                name: 'agent_access_item',
                jsonName: 'agentAccessItem',
                kind: 'message',
                oneof: 'content',
                T: () => AgentAccessItem,
            },
        ]);
    }
    create(value?: PartialMessage<ActionPayload>): ActionPayload {
        const message = globalThis.Object.create(this.messagePrototype!);
        message.content = { oneofKind: undefined };
        if (value !== undefined) reflectionMergePartial<ActionPayload>(this, message, value);
        return message;
    }
    internalBinaryRead(
        reader: IBinaryReader,
        length: number,
        options: BinaryReadOptions,
        target?: ActionPayload
    ): ActionPayload {
        let message = target ?? this.create();
        const end = reader.pos + length;
        while (reader.pos < end) {
            const [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    message.content = {
                        oneofKind: 'agentAccessItem',
                        agentAccessItem: AgentAccessItem.internalBinaryRead(
                            reader,
                            reader.uint32(),
                            options,
                            (message.content as any).agentAccessItem
                        ),
                    };
                    break;
                default:
                    const u = options.readUnknownField;
                    if (u === 'throw')
                        throw new globalThis.Error(
                            `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`
                        );
                    const d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActionPayload, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        if (message.content.oneofKind === 'agentAccessItem')
            AgentAccessItem.internalBinaryWrite(
                message.content.agentAccessItem,
                writer.tag(1, WireType.LengthDelimited).fork(),
                options
            ).join();
        const u = options.writeUnknownFields;
        if (u !== false) (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
export const ActionPayload = new ActionPayload$Type();
