angular.module('proton.message')
    .directive('messageAutoGenerated', () => {

        return {
            replace: true,
            restrict: 'E',
            templateUrl: 'templates/message/messageAutoGenerated.tpl.html'
        };
    });
