export const START_EVENT_MANAGER = 'START_EVENT_MANAGER';
export const STOP_EVENT_MANAGER = 'STOP_EVENT_MANAGER';
export const GET_EVENTS = 'GET_EVENTS';
export const RESET_EVENT_MANAGER = 'RESET_EVENT_MANAGER';
