/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export namespace biometric {
  export function canCheckPresence(): Promise<boolean>
  export function checkPresence(handle: Buffer, reason: string): Promise<boolean>
  export function getDecryptionKey(challenge?: string | undefined | null): Promise<Array<string>>
  export function getSecret(key: string): Promise<string>
  export function setSecret(key: string, secret: string): Promise<void>
  export function deleteSecret(key: string): Promise<void>
}
