/* auto-generated by NAPI-RS; eslint and tslint are still enabled for e.g. Uint8Array normalization */

export declare namespace biometric {
    export function canCheckPresence(): Promise<boolean>;
    export function checkPresence(handle: Buffer, reason: string): Promise<void>;
    export function getSecret(key: string): Promise<Uint8Array<ArrayBuffer>>;
    export function setSecret(key: string, secret: Uint8Array<ArrayBuffer>): Promise<void>;
    export function deleteSecret(key: string): Promise<void>;
}
export declare namespace clipboard {
    export function writeText(text: string, sensitive: boolean): Promise<void>;
    export function read(): Promise<string>;
}
