export enum AUTH_LOG_EVENTS {
    LOGIN_FAILURE_PASSWORD = 0,
    LOGIN_SUCCESS,
    LOGOUT,
    LOGIN_FAILURE_2FA,
    LOGIN_SUCCESS_AWAIT_2FA,

    REAUTH_FAILURE_PASSWORD = 10,
    REAUTH_FAILURE_2FA,
    REAUTH_SUCCESS,

    CHANGE_ACCOUNT_PASSWORD = 20,
    CHANGE_MAILBOX_PASSWORD,
    RESET_ACCOUNT,

    ENABLE_MAILBOX_PASSWORD = 30,
    DISABLE_MAILBOX_PASSWORD,
    ENABLE_TOTP,
    DISABLE_TOTP,
    ADD_U2F,
    REMOVE_U2F,
}

export interface AuthLog {
    AppVersion: string;
    Event: AUTH_LOG_EVENTS;
    IP: string;
    Time: number;
}
