/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Screen views during the signup.
 */
export interface MeProtonCoreObservabilityDomainMetricsSignupScreenViewTotalV1 {
  Labels: {
    screen_id:
      | "chooseExternalEmail"
      | "chooseInternalEmail"
      | "chooseUsername"
      | "createPassword"
      | "setRecoveryMethod"
      | "congratulations";
  };
  Value: number;
}
