/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tracks the success or failure of the POST request to `/auth/v4/info` and `/auth/v4`.
 */
export interface MeProtonCoreObservabilityDomainMetricsAuthV4RequestMetric {
  Labels: {
    status: "success" | "http4xx" | "http5xx" | "network_error" | "serialization_error" | "unknown";
  };
  Value: number;
}
