/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Perform an auth, using mailbox passwird.
 */
export interface MeProtonCoreObservabilityDomainMetricsSigninSubmitMailboxPasswordTotal {
  Labels: {
    status:
      | "success"
      | "http4xx"
      | "http5xx"
      | "network_error"
      | "serialization_error"
      | "key_derivation_failed"
      | "key_unlock_failed"
      | "unknown";
  };
  Value: number;
}
