/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of number of times a UI blocking error page is displayed.
 */
export interface HttpsProtonMeCoreUiBlockingErrorPageTotalV1SchemaJson {
  Labels: {};
  Value: number;
}
