/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Screen views for account recovery
 */
export interface MeProtonCoreObservabilityDomainMetricsAccountRecoveryScreenViewTotal {
  Labels: {
    screen_id:
      | "gracePeriodInfo"
      | "cancelResetPassword"
      | "passwordChangeInfo"
      | "recoveryCancelledInfo"
      | "recoveryExpiredInfo";
  };
  Value: number;
}
