/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of document updates failed to be sent to the server and saved.
 */
export interface HttpsProtonMeDocsDocumentUpdatesSaveErrorTotalV1SchemaJson {
  Labels: {
    type: "server_error" | "network_error" | "update_too_big" | "document_too_big" | "unknown";
  };
  Value: number;
}
