/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Users success rate (every 5min)
 */
export interface HttpsProtonMeDocsUsersSuccessRateTotalV1SchemaJson {
  Labels: {
    plan: "free" | "paid";
    critical: "true" | "false";
    error: "true" | "false";
    sentry: "true" | "false";
  };
  Value: number;
}
