/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of suggestions created.
 */
export interface HttpsProtonMeDocsSuggestionsCreatedTotalV1SchemaJson {
  Labels: {
    type: "insertion" | "replacement" | "deletion" | "formatting" | "style" | "other";
  };
  Value: number;
}
