 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of disconnects to RTS.
 */
export interface HttpsProtonMeDocsRealtimeDisconnectErrorTotalV2SchemaJson {
  Labels: {
    type:
      | "normal_closure"
      | "going_away"
      | "protocol_error"
      | "unsupported_data"
      | "no_status_received"
      | "abnormal_closure"
      | "invalid_frame_payload_data"
      | "policy_violation"
      | "message_too_big"
      | "missing_extension"
      | "internal_error"
      | "service_restart"
      | "try_again_later"
      | "bad_gateway"
      | "tls_handshake"
      | "stale_commit_id"
      | "document_not_found"
      | "invalid_parameters"
      | "unauthorized"
      | "timeout"
      | "document_timeout"
      | "left"
      | "traffic_abuse_max_bandwidth"
      | "traffic_abuse_max_du_size"
      | "kill_switch_enabled"
      | "document_capacity_reached"
      | "document_recreating"
      | "document_participant_limit_reached"
      | "client_version_not_supported"
      | "user_permissions_to_document_changed"
      | "document_is_inaccessible"
      | "document_cleanup"
      | "dc_emptying"
      | "room_creation_failed"
      | "message_broker_connection_lost"
      | "session_ping_error"
      | "websocket_message_handling_error"
      | "room_joining_error"
      | "connection_configuring_error";
  };
  Value: number;
}
