/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Latency of the real-time edits to reach participants
 */
export interface HttpsProtonMeDocsRealtimeEditLatencyHistogramV1SchemaJson {
  Labels: {};
  Value: number;
}
