/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of failed websocket connections
 */
export interface HttpsProtonMeDocsFailedWebsocketConnectionsTotalV1SchemaJson {
  Labels: {
    retry: "true" | "false";
    type: "server_error" | "network_error" | "unknown";
  };
  Value: number;
}
