/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count how many comments and replies are generated
 */
export interface HttpsProtonMeDocsCommentsTotalV1SchemaJson {
  Labels: {
    type: "comment" | "reply";
  };
  Value: number;
}
