 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of sheets yjs drift detected.
 */
export interface HttpsProtonMeDocsSheetsYjsDriftDetectedTotalV1SchemaJson {
  Labels: {
    reason: "local-differs-from-yjs" | "local-change-not-observed-by-yjs";
  };
  Value: number;
}
