/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter for number of open documents using a heartbeat mechanism (pinging every x seconds)
 */
export interface HttpsProtonMeDocsOpenDocumentsHeartbeatTotalV1SchemaJson {
  Labels: {
    browser: "chrome" | "firefox" | "safari" | "edge" | "native-ios" | "native-android" | "other";
  };
  Value: number;
}
