/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of document updates that were not acknowledged in time by the RTS
 */
export interface HttpsProtonMeDocsDocumentUpdatesAckErrorTotalV1SchemaJson {
  Labels: {
    type: "concern_threshold" | "error_threshold";
  };
  Value: number;
}
