/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counter of commit ID out of sync error encountered when fetching RTS token.
 */
export interface HttpsProtonMeDocsCommitIdOutOfSyncTotalV1SchemaJson {
  Labels: {};
  Value: number;
}
