 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count and reason for document open redirect
 */
export interface HttpsProtonMeDocsDocumentOpenRedirectHistogramV1SchemaJson {
  Labels: {
    cause:
      | "navigate_to_action"
      | "docs_disabled_redirect"
      | "sheets_disabled_redirect"
      | "reauth_public_redirect"
      | "invite_accept_public_redirect"
      | "invite_accept_reload"
      | "editor_client_reload"
      | "editor_content_window_reload"
      | "correct_doc_type_redirect"
      | "public_to_authed_redirect"
      | "invalid_session_fork"
      | "public_copier_open_window"
      | "unknown";
  };
  Value: number;
}
