 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count how many times connection from client to RTS is ready (i.e. receives server ready event message)
 */
export interface HttpsProtonMeDocsConnectionReadyTotalV1SchemaJson {
  Labels: {
    type: "success" | "timeout";
    visibility: "public" | "private";
    docType: "document" | "spreadsheet";
  };
  Value: number;
}
