/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Percentage of total upload time spent on the transfer when a file is uploaded via the multi-block path
 */
export interface HttpsProtonMeDriveSdkUploadLargeFileActiveTimeShareHistogramV1SchemaJson {
  Value: number;
  Labels: {
    sizeClass: "small" | "single" | "multi";
  };
}
