/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Drive verification issues
 */
export interface HttpsProtonMeDriveSdkIntegrityVerificationErrorsTotalV2SchemaJson {
  Labels: {
    field:
      | "shareKey"
      | "membershipInviter"
      | "membershipInvitee"
      | "nodeKey"
      | "nodeName"
      | "nodeHashKey"
      | "nodeExtendedAttributes"
      | "nodeContentKey"
      | "content";
    addressMatchingDefaultShare: "yes" | "no" | "unknown";
    recency: "past_month" | "past_year" | "since_2024" | "before_2024" | "unknown";
    causedBy: "1p" | "3p-sdk" | "3p" | "unknown";
  };
  Value: number;
}
