/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures the number of successful resync events
 */
export interface HttpsProtonMeDriveSyncResyncSuccessTotalV1SchemaJson {
  Labels: {
    status: "completed" | "cancelled" | "failed";
    retry: "true" | "false";
  };
  Value: number;
}
