/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures specific error counts during upload
 */
export interface HttpsProtonMeDriveUploadErrorsTotalV2SchemaJson {
  Labels: {
    type:
      | "free_space_exceeded"
      | "too_many_children"
      | "network_error"
      | "server_error"
      | "integrity_error"
      | "rate_limited"
      | "4xx"
      | "5xx"
      | "unknown";
    shareType: "main" | "device" | "photo" | "shared" | "shared_public" | "shared_photo";
    initiator: "background" | "explicit";
  };
  Value: number;
}
