 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures how often a file has no thumbnail handler at all
 */
export interface HttpsProtonMeDriveThumbnailNoHandlerTotalV1SchemaJson {
  Labels: {};
  Value: number;
}
