 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Tracks the time to load first content after opening a tab.
 */
export interface HttpsProtonMeDriveMobilePerformanceTabToFirstItemHistogramV1SchemaJson {
  Labels: {
    pageType: "my_files" | "computers" | "photos" | "shared_by_me" | "shared_with_me" | "trash";
    loadType: "first" | "subsequent";
  };
  Value: number;
}
