 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures specific error counts during thumbnail generation, broken down by handler and failure stage
 */
export interface HttpsProtonMeDriveThumbnailErrorsTotalV1SchemaJson {
  Labels: {
    handler: "image" | "heic" | "raw" | "svg" | "video" | "cbz";
    errorType:
      | "unsupported_format"
      | "corrupted"
      | "missing_data"
      | "thumbnail_size"
      | "timeout"
      | "canvas"
      | "encoding"
      | "file_load"
      | "other";
  };
  Value: number;
}
