 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures the proportion of successful vs failed thumbnail generations, broken down by handler
 */
export interface HttpsProtonMeDriveThumbnailSuccessRateTotalV1SchemaJson {
  Labels: {
    handler: "image" | "heic" | "raw" | "svg" | "video" | "cbz";
    status: "success" | "failed";
  };
  Value: number;
}
