/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Drive verification issues
 */
export interface HttpsProtonMeDriveSdkIntegrityBlockVerificationErrorsTotalV1SchemaJson {
  Labels: {
    retryHelped: "yes" | "no";
  };
  Value: number;
}
