 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count number of accesses that took too long due to being loaded in parallel by another call
 */
export interface HttpsProtonMeDriveSdkDebounceTotalV1SchemaJson {
  Labels: {};
  Value: number;
}
