/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count of unique successful or failed downloads
 */
export interface HttpsProtonMeDriveSdkDownloadSuccessRateTotalV1SchemaJson {
  Labels: {
    volumeType: "own_volume" | "own_photo_volume" | "shared" | "shared_public" | "unknown";
    status: "success" | "failure";
  };
  Value: number;
}
