 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Erroring users (every 5min)
 */
export interface HttpsProtonMeDriveErrorErroringUsersTotalV1SchemaJson {
  Labels: {
    plan: "free" | "paid" | "anonymous" | "unknown";
    crashError: "true" | "false";
    coreFeatureError: "true" | "false";
    otherError: "true" | "false";
  };
  Value: number;
}
