 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Absolute counter for Drive errors by category
 */
export interface MeProtonDriveObservabilityDomainMetricsDriveErrorTotal {
  Labels: {
    category: "crashError" | "coreFeatureError" | "otherError";
  };
  Value: number;
}
