/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counts of error categories during upload
 */
export interface HttpsProtonMeDriveSdkUploadErrorsTotalV1SchemaJson {
  Labels: {
    volumeType: "own_volume" | "own_photo_volume" | "shared" | "shared_public" | "unknown";
    type: "server_error" | "network_error" | "integrity_error" | "rate_limited" | "4xx" | "unknown";
  };
  Value: number;
}
