 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Drive file download verification
 */
export interface HttpsProtonMeDriveDownloadVerifierAttemptsTotalV1SchemaJson {
  Labels: {
    result: "success" | "failure" | "skipped";
    fileSize: "2**10" | "2**20" | "2**22" | "2**25" | "2**30" | "xxxxl";
  };
  Value: number;
}
