/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count number of API retry events that succeeded after retry
 */
export interface HttpsProtonMeDriveSdkApiRetrySucceededTotalV1SchemaJson {
  Labels: {
    volumeType: "own_volume" | "own_photo_volume" | "shared" | "shared_public" | "unknown";
  };
  Value: number;
}
