/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures number of synced items
 */
export interface HttpsProtonMeDriveSyncItemsTotalV1SchemaJson {
  Labels: {
    type: "local_sync" | "remote_sync";
    shareType: "own" | "device" | "photo" | "shared";
  };
  Value: number;
}
