/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures number of event updates (not event fetches)
 */
export interface HttpsProtonMeDriveSyncEventUpdatesTotalV1SchemaJson {
  Labels: {
    volumeType: "own" | "shared";
  };
  Value: number;
}
