/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures how many users experienced error in the past 10 minutes
 */
export interface HttpsProtonMeDriveUploadErroringUsersTotalV2SchemaJson {
  Labels: {
    plan: "free" | "paid";
    shareType: "main" | "device" | "photo" | "shared";
    initiator: "background" | "explicit";
  };
  Value: number;
}
