/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * At what point the upload failed - how many bytes were uploaded before failure
 */
export interface HttpsProtonMeDriveSdkUploadErrorsTransferSizeHistogramV1SchemaJson {
  Value: number;
  Labels: {};
}
