 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures file content upload speed (in kiB/s)
 */
export interface HttpsProtonMeDriveUploadSpeedHistogramV1SchemaJson {
  Labels: {
    context: "foreground" | "background";
    pipeline: "default" | "legacy";
  };
  Value: number;
}
