/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Count number of events per event type
 */
export interface HttpsProtonMeDriveSyncEventTotalV2SchemaJson {
  Labels: {
    eventType: "create" | "delete" | "update" | "update_metadata";
    volumeType: "main" | "shared";
  };
  Value: number;
}
