 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures how many cancellation can occur for a worker with its reason
 */
export interface HttpsProtonMeDriveUploadWorkerCancellationTotalV1SchemaJson {
  Labels: {
    pipeline: "default" | "legacy";
    initiator: "background" | "explicit";
    reason: "user" | "constraint" | "timeout" | "os_limit" | "other" | "unknown";
    fileSize: "2**10" | "2**20" | "2**22" | "2**25" | "2**30" | "xxxxl";
  };
  Value: number;
}
