/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A series that measures this and that
 */
export interface MyDataSeriesV2 {
    Value: number;
    Labels: {
        foo: 'bar' | 'baz';
        foo_bar: 'foobar' | 'foobaz';
    };
}
