 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Lifecycle of an incremental update batch. Together the success/failure outcomes give the incremental update success rate.
 */
export interface HttpsProtonMeWebDriveSearchIncrementalUpdateTotalV1SchemaJson {
  Labels: {
    outcome: "success" | "failure";
  };
  Value: number;
}
