/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures the total number of page loads for the web signup steps
 */
export interface WebCoreSignupPageLoadTotal {
  Value: number;
  Labels: {
    step:
      | "external_account_creation"
      | "proton_account_creation"
      | "verification"
      | "referral"
      | "upsell"
      | "payment"
      | "loading"
      | "congratulations"
      | "recovery"
      | "explore";
    application: "proton-vpn-settings" | "proton-account";
  };
}
