 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counts users turning search on. manual = the user opted in manually and legacy search was not enabled. legacy_auto_upgrade = legacy search was already enabled and was upgraded automatically.
 */
export interface HttpsProtonMeWebDriveSearchOptInTotalV1SchemaJson {
  Labels: {
    kind: "manual" | "legacy_auto_upgrade";
  };
  Value: number;
}
