/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures the session recovery password reset available account modal loads
 */
export interface WebCoreSessionRecoveryPasswordResetAvailableAccountModalLoadTotal {
  Value: number;
  Labels: {
    step: "info" | "password" | "confirm_cancellation";
  };
}
