 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Time taken to process event loop cycles for v6 event loops
 */
export interface EventLoopProcessingTimeV6 {
  Value: number;
  Labels: {
    has_more: "true" | "false";
    event_loop_type: "core" | "mail" | "calendar" | "contact";
    api_calls_count: "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10+";
    api_failures_count: "0" | "1" | "2" | "3" | "4" | "5+";
    interval_since_last_ms: "<1000" | "1000-5000" | "5000-10000" | "10000-30000" | "30000+";
  };
}
