 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Size of the search index in megabytes.
 */
export interface HttpsProtonMeWebDriveSearchIndexSizeHistogramV1SchemaJson {
  Labels: {
    searchVersion: "legacy" | "v1";
  };
  Value: number;
}
