 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Wall-clock time in seconds to process one batch of incremental events.
 */
export interface HttpsProtonMeWebDriveSearchIncrementalUpdateTimeHistogramV1SchemaJson {
  Labels: {};
  Value: number;
}
