 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counts search errors that could not be classified into any known error kind.
 */
export interface HttpsProtonMeWebDriveSearchOtherErrorTotalV1SchemaJson {
  Labels: {};
  Value: number;
}
