 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Drive web various warnings
 */
export interface HttpsProtonMeWebDriveWarningsTotalV1SchemaJson {
  Labels: {
    warning: "app_outdated" | "cannot_init_sw" | "cannot_create_small_enough_thumbnail";
  };
  Value: number;
}
