 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Outcome of a full re-index run. Together the success/failure outcomes give the bootstrap success rate.
 */
export interface HttpsProtonMeWebDriveSearchInitialIndexingTotalV1SchemaJson {
  Labels: {
    outcome: "success" | "failure";
  };
  Value: number;
}
