 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Persisted size in megabytes of the search index in IndexedDB, sampled once at startup after bootstrap.
 */
export interface HttpsProtonMeWebDriveSearchIndexSizeHistogramV2SchemaJson {
  Labels: {
    searchVersion: "legacy" | "v1";
  };
  Value: number;
}
