/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measures the number of times the setup sso domain modal is loaded
 */
export interface WebCoreSSOSetupDomainModalLoadTotal {
  Value: number;
  Labels: {
    step: "domain-input" | "txt-record";
  };
}
