 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counts search worker health incidents, labelled by category.
 */
export interface HttpsProtonMeWebDriveSearchWorkerHealthTotalV1SchemaJson {
  Labels: {
    category:
      | "search-worker-heartbeat-timeout"
      | "search-worker-heartbeat-error"
      | "search-worker-reconnect-failure"
      | "main-thread-timeout";
  };
  Value: number;
}
