/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Latency of clickToLastItemRendered event, representing the moment the very last item is rendered (if ever it renders).
 */
export interface HttpsProtonMeWebDrivePerformanceClicktolastitemrenderedHistogramV1SchemaJson {
  Labels: {
    view: "list" | "grid";
    pageType: "filebrowser" | "computers" | "photos" | "shared_by_me" | "shared_with_me" | "trash";
  };
  Value: number;
}
