 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Counts indexer crashes that will not auto-recover, labelled by error kind.
 */
export interface HttpsProtonMeWebDriveSearchPermanentErrorsTotalV1SchemaJson {
  Labels: {
    errorKind: "search_library_error" | "invalid_indexer_state" | "corrupted_db" | "quota_exceeded" | "unknown";
  };
  Value: number;
}
