/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Public share link unsuccessful page loads
 */
export interface HttpsProtonMeWebDrivePublicShareLoadErrorTotalV1SchemaJson {
  Labels: {
    error: "unknown" | "crypto" | "4xx" | "5xx" | "does_not_exist_or_expired";
    type: "file" | "folder" | "unknown";
    plan: "not_recognized" | "free" | "paid";
  };
  Value: number;
}
