 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Outcome of a user-issued search query. Together the success/failure outcomes give the search query success rate.
 */
export interface HttpsProtonMeWebDriveSearchQueryTotalV1SchemaJson {
  Labels: {
    outcome: "success" | "failure";
  };
  Value: number;
}
