/* tslint:disable */
/* eslint-disable */
/**
* @returns {string}
*/
export function library_version(): string;
/**
*/
export enum WasmError {
  InvalidSecretKey = 0,
  InvalidDescriptor = 1,
  InvalidDerivationPath = 2,
  InvalidAccountIndex = 3,
  DerivationError = 4,
  SyncError = 5,
  OutpointParsingError = 6,
  InvalidData = 7,
  InvalidTxId = 8,
  CannotComputeTxFees = 9,
  InvalidMnemonic = 10,
  InvalidSeed = 11,
  Generic = 12,
  NoRecipients = 13,
  NoUtxosSelected = 14,
  OutputBelowDustLimit = 15,
  InsufficientFunds = 16,
  BnBTotalTriesExceeded = 17,
  BnBNoExactMatch = 18,
  UnknownUtxo = 19,
  TransactionNotFound = 20,
  TransactionConfirmed = 21,
  IrreplaceableTransaction = 22,
  FeeRateTooLow = 23,
  FeeTooLow = 24,
  FeeRateUnavailable = 25,
  MissingKeyOrigin = 26,
  Key = 27,
  ChecksumMismatch = 28,
  SpendingPolicyRequired = 29,
  InvalidPolicyPathError = 30,
  Signer = 31,
  InvalidOutpoint = 32,
  Descriptor = 33,
  Miniscript = 34,
  MiniscriptPsbt = 35,
  Bip32 = 36,
  Psbt = 37,
}
/**
*/
export enum WasmLanguage {
  English = 0,
  SimplifiedChinese = 1,
  TraditionalChinese = 2,
  Czech = 3,
  French = 4,
  Italian = 5,
  Japanese = 6,
  Korean = 7,
  Spanish = 8,
}
/**
*/
export enum WasmSupportedBIPs {
  Bip44 = 0,
  Bip49 = 1,
  Bip84 = 2,
  Bip86 = 3,
}
/**
*/
export enum WasmNetwork {
/**
* Mainnet Bitcoin.
*/
  Bitcoin = 0,
/**
* Bitcoin's testnet network.
*/
  Testnet = 1,
/**
* Bitcoin's signet network.
*/
  Signet = 2,
/**
* Bitcoin's regtest network.
*/
  Regtest = 3,
}
/**
*/
export enum WasmWordCount {
  Words12 = 0,
  Words15 = 1,
  Words18 = 2,
  Words21 = 3,
  Words24 = 4,
}
/**
*/
export enum WasmKeychainKind {
/**
* External keychain, used for deriving recipient addresses.
*/
  External = 0,
/**
* Internal keychain, used for deriving change addresses.
*/
  Internal = 1,
}
/**
*/
export class DetailledWasmError {
  free(): void;
/**
*/
  details: any;
/**
*/
  kind: WasmError;
}
/**
*/
export class ExportedStringVec {
  free(): void;
/**
* @param {number} index
* @returns {string}
*/
  get_name(index: number): string;
}
/**
*/
export class WasmAccount {
  free(): void;
/**
* @param {string} mnemonic_str
* @param {string | undefined} passphrase
* @param {WasmAccountConfig} config
*/
  constructor(mnemonic_str: string, passphrase: string | undefined, config: WasmAccountConfig);
/**
* @returns {Promise<void>}
*/
  sync(): Promise<void>;
/**
* @returns {WasmBalance}
*/
  get_balance(): WasmBalance;
/**
* @param {WasmPagination} pagination
* @returns {(WasmSimpleTransaction)[]}
*/
  get_transactions(pagination: WasmPagination): (WasmSimpleTransaction)[];
}
/**
*/
export class WasmAccountConfig {
  free(): void;
/**
* @param {WasmSupportedBIPs | undefined} [bip]
* @param {WasmNetwork | undefined} [network]
* @param {number | undefined} [account_index]
*/
  constructor(bip?: WasmSupportedBIPs, network?: WasmNetwork, account_index?: number);
/**
*/
  account_index: number;
/**
*/
  bip: WasmSupportedBIPs;
/**
*/
  network: WasmNetwork;
}
/**
*/
export class WasmAddressIndex {
  free(): void;
/**
* @returns {WasmAddressIndex}
*/
  static createNew(): WasmAddressIndex;
/**
* @returns {WasmAddressIndex}
*/
  static createLastUnused(): WasmAddressIndex;
/**
* @param {number} index
* @returns {WasmAddressIndex}
*/
  static createPeek(index: number): WasmAddressIndex;
}
/**
*/
export class WasmAddressInfo {
  free(): void;
/**
* @returns {string}
*/
  to_string(): string;
/**
*/
  readonly index: number;
}
/**
*/
export class WasmBalance {
  free(): void;
/**
* Confirmed and immediately spendable balance
*/
  confirmed: bigint;
/**
* All coinbase outputs not yet matured
*/
  immature: bigint;
/**
* Unconfirmed UTXOs generated by a wallet tx
*/
  trusted_pending: bigint;
/**
* Unconfirmed UTXOs received from an external wallet
*/
  untrusted_pending: bigint;
}
/**
*/
export class WasmConfirmation {
  free(): void;
/**
*/
  confirmation_time?: bigint;
/**
*/
  confirmed: boolean;
/**
*/
  last_seen?: bigint;
}
/**
*/
export class WasmDerivationPath {
  free(): void;
/**
* @param {string} path
*/
  constructor(path: string);
}
/**
*/
export class WasmLockTime {
  free(): void;
/**
* @param {number} height
* @returns {WasmLockTime}
*/
  static fromHeight(height: number): WasmLockTime;
/**
* @param {number} seconds
* @returns {WasmLockTime}
*/
  static fromSeconds(seconds: number): WasmLockTime;
/**
* @returns {boolean}
*/
  is_block_height(): boolean;
/**
* @returns {boolean}
*/
  is_block_time(): boolean;
/**
* @returns {number}
*/
  to_consensus_u32(): number;
}
/**
*/
export class WasmMnemonic {
  free(): void;
/**
* Generates a Mnemonic with a random entropy based on the given word count.
* @param {WasmWordCount} word_count
*/
  constructor(word_count: WasmWordCount);
/**
* Parse a Mnemonic with the given string.
* @param {string} mnemonic
* @returns {WasmMnemonic}
*/
  static fromString(mnemonic: string): WasmMnemonic;
/**
* Create a new Mnemonic from the given entropy.
* @param {Uint8Array} entropy
* @returns {WasmMnemonic}
*/
  static fromEntropy(entropy: Uint8Array): WasmMnemonic;
/**
* Returns the Mnemonic as a string.
* @returns {string}
*/
  asString(): string;
/**
* @returns {(string)[]}
*/
  toWords(): (string)[];
}
/**
* Serialised Outpoint under the form <txid>:<index>
*/
export class WasmOutPoint {
  free(): void;
}
/**
*/
export class WasmPagination {
  free(): void;
/**
* @param {number} skip
* @param {number} take
*/
  constructor(skip: number, take: number);
/**
*/
  skip: number;
/**
*/
  take: number;
}
/**
*/
export class WasmPartiallySignedTransaction {
  free(): void;
}
/**
*/
export class WasmScript {
  free(): void;
/**
*/
  0: Uint8Array;
}
/**
*/
export class WasmSequence {
  free(): void;
/**
*/
  0: number;
}
/**
*/
export class WasmSimpleTransaction {
  free(): void;
/**
*/
  confirmation: WasmConfirmation;
/**
*/
  fees?: bigint;
/**
*/
  txid: string;
/**
*/
  value: bigint;
}
/**
*/
export class WasmTransaction {
  free(): void;
/**
*/
  input: (WasmTxIn)[];
/**
*/
  lock_time: WasmLockTime;
/**
*/
  output: (WasmTxOut)[];
/**
*/
  version: number;
}
/**
*/
export class WasmTxBuilder {
  free(): void;
/**
*/
  constructor();
/**
* @param {WasmScript} script
* @param {bigint} amount
* @returns {WasmTxBuilder}
*/
  add_recipient(script: WasmScript, amount: bigint): WasmTxBuilder;
/**
* @param {number} index
* @returns {WasmTxBuilder}
*/
  remove_recipient(index: number): WasmTxBuilder;
/**
* @param {number} index
* @param {WasmScript | undefined} [script]
* @param {bigint | undefined} [amount]
* @returns {WasmTxBuilder}
*/
  update_recipient(index: number, script?: WasmScript, amount?: bigint): WasmTxBuilder;
/**
*
*     * UTXOs
*     
* @param {WasmOutPoint} outpoint
* @returns {WasmTxBuilder}
*/
  add_unspendable_utxo(outpoint: WasmOutPoint): WasmTxBuilder;
/**
* @param {WasmOutPoint} outpoint
* @returns {WasmTxBuilder}
*/
  remove_unspendable_utxo(outpoint: WasmOutPoint): WasmTxBuilder;
/**
* @param {WasmOutPoint} outpoint
* @returns {WasmTxBuilder}
*/
  add_utxo_to_spend(outpoint: WasmOutPoint): WasmTxBuilder;
/**
* @param {WasmOutPoint} outpoint
* @returns {WasmTxBuilder}
*/
  remove_utxo_to_spend(outpoint: WasmOutPoint): WasmTxBuilder;
/**
*
*     * Coin selection enforcement
*     
* @returns {WasmTxBuilder}
*/
  manually_selected_only(): WasmTxBuilder;
/**
*
*     * Change policy
*     
* @returns {WasmTxBuilder}
*/
  do_not_spend_change(): WasmTxBuilder;
/**
* @returns {WasmTxBuilder}
*/
  only_spend_change(): WasmTxBuilder;
/**
* @returns {WasmTxBuilder}
*/
  allow_spend_both(): WasmTxBuilder;
/**
*
*     * Fees
*     
* @param {number} sat_per_vb
* @returns {WasmTxBuilder}
*/
  fee_rate(sat_per_vb: number): WasmTxBuilder;
/**
* @param {bigint} fee_amount
* @returns {WasmTxBuilder}
*/
  fee_absolute(fee_amount: bigint): WasmTxBuilder;
/**
*
*     * Final
*     
* @param {WasmAccount} wasm_account
* @returns {WasmPartiallySignedTransaction}
*/
  create_pbst(wasm_account: WasmAccount): WasmPartiallySignedTransaction;
}
/**
*/
export class WasmTxIn {
  free(): void;
/**
*/
  previous_output: WasmOutPoint;
/**
*/
  script_sig: WasmScript;
/**
*/
  sequence: WasmSequence;
}
/**
*/
export class WasmTxOut {
  free(): void;
/**
*/
  script_pubkey: WasmScript;
/**
*/
  value: bigint;
}
/**
*/
export class WasmWallet {
  free(): void;
/**
* @param {string} bip39_mnemonic
* @param {string | undefined} bip38_passphrase
* @param {WasmWalletConfig} config
*/
  constructor(bip39_mnemonic: string, bip38_passphrase: string | undefined, config: WasmWalletConfig);
/**
* @param {WasmSupportedBIPs} bip
* @param {number} account_index
* @returns {Promise<void>}
*/
  add_account(bip: WasmSupportedBIPs, account_index: number): Promise<void>;
/**
* @returns {Promise<WasmBalance>}
*/
  get_balance(): Promise<WasmBalance>;
/**
* @returns {string}
*/
  get_fingerprint(): string;
}
/**
*/
export class WasmWalletConfig {
  free(): void;
/**
* @param {WasmNetwork | undefined} [network]
*/
  constructor(network?: WasmNetwork);
/**
*/
  network: WasmNetwork;
}
