import actionMessage from './directives/actionMessage';
import allMessageLabels from './directives/allMessageLabels';
import displayContentBtn from './directives/displayContentBtn';
import embeddedImgLoader from './directives/embeddedImgLoader';
import filterButton from './directives/filterButton';
import foldersMessage from './directives/foldersMessage';
import injectMessageMedia from './directives/injectMessageMedia';
import mailTo from './directives/mailTo';
import message from './directives/message';
import messageAutoGenerated from './directives/messageAutoGenerated';
import messageComposeTo from './directives/messageComposeTo';
import messageContacts from './directives/messageContacts';
import messageExtra from './directives/messageExtra';
import messagePgpAttachments from './directives/messagePgpAttachments';
import messageSpamScore from './directives/messageSpamScore';
import messageView from './directives/messageView';
import renderMessageBody from './directives/renderMessageBody';
import toggleBlockquote from './directives/toggleBlockquote';
import toggleMessage from './directives/toggleMessage';
import unsubscribePanel from './directives/unsubscribePanel';
import displayContent from './factories/displayContent';
import displayEmbedded from './factories/displayEmbedded';
import displayImages from './factories/displayImages';
import messageActions from './factories/messageActions';
import messageApi from './factories/messageApi';
import messageModel from './factories/messageModel';
import plusAliasModel from './factories/plusAliasModel';
import signatureBuilder from './factories/signatureBuilder';
import simpleSend from './factories/simpleSend';
import unsubscribeModel from './factories/unsubscribeModel';
import filterMessages from './filters/filterMessages';
import messageTime from './filters/messageTime';
import nameRecipient from './filters/nameRecipient';
import recipients from './filters/recipients';
import findExpendableMessage from './services/findExpendableMessage';
import messageBuilder from './services/messageBuilder';
import prepareContent from './services/prepareContent';
import transformAttachements from './services/transformAttachements';
import transformBlockquotes from './services/transformBlockquotes';
import transformEmbedded from './services/transformEmbedded';
import transformEscape from './services/transformEscape';
import transformLinks from './services/transformLinks';
import transformRemote from './services/transformRemote';
import transformStylesheet from './services/transformStylesheet';
import transformWelcome from './services/transformWelcome';
import messageDisplayError from './directives/messageDisplayError';

export default angular
    .module('proton.message', ['ngSanitize', 'proton.contact', 'proton.squire'])
    .directive('messageDisplayError', messageDisplayError)
    .run((unsubscribeModel) => unsubscribeModel.init())
    .directive('actionMessage', actionMessage)
    .directive('allMessageLabels', allMessageLabels)
    .directive('displayContentBtn', displayContentBtn)
    .directive('embeddedImgLoader', embeddedImgLoader)
    .directive('filterButton', filterButton)
    .directive('foldersMessage', foldersMessage)
    .directive('injectMessageMedia', injectMessageMedia)
    .directive('mailTo', mailTo)
    .directive('message', message)
    .directive('messageAutoGenerated', messageAutoGenerated)
    .directive('messageComposeTo', messageComposeTo)
    .directive('messageContacts', messageContacts)
    .directive('messageExtra', messageExtra)
    .directive('messagePgpAttachments', messagePgpAttachments)
    .directive('messageSpamScore', messageSpamScore)
    .directive('messageView', messageView)
    .directive('renderMessageBody', renderMessageBody)
    .directive('toggleBlockquote', toggleBlockquote)
    .directive('toggleMessage', toggleMessage)
    .directive('unsubscribePanel', unsubscribePanel)
    .factory('displayContent', displayContent)
    .factory('displayEmbedded', displayEmbedded)
    .factory('displayImages', displayImages)
    .factory('messageActions', messageActions)
    .factory('messageApi', messageApi)
    .factory('messageModel', messageModel)
    .factory('plusAliasModel', plusAliasModel)
    .factory('signatureBuilder', signatureBuilder)
    .factory('simpleSend', simpleSend)
    .factory('unsubscribeModel', unsubscribeModel)
    .filter('filterMessages', filterMessages)
    .filter('messageTime', messageTime)
    .filter('nameRecipient', nameRecipient)
    .filter('recipients', recipients)
    .factory('findExpendableMessage', findExpendableMessage)
    .factory('messageBuilder', messageBuilder)
    .factory('prepareContent', prepareContent)
    .factory('transformAttachements', transformAttachements)
    .factory('transformBlockquotes', transformBlockquotes)
    .factory('transformEmbedded', transformEmbedded)
    .factory('transformEscape', transformEscape)
    .factory('transformLinks', transformLinks)
    .factory('transformRemote', transformRemote)
    .factory('transformStylesheet', transformStylesheet)
    .factory('transformWelcome', transformWelcome).name;
