/**
 * Actions emitted by the spreadsheet editor.
 *
 * The Docs host translates these readable strings to its numeric storage contract.
 * Matching keys and values preserve enum-style access without hiding the string contract behind a type assertion.
 */
export const SheetsActions = {
  SetLocale: 'SetLocale',
  FreezeRows: 'FreezeRows',
  UnfreezeRows: 'UnfreezeRows',
  FreezeColumns: 'FreezeColumns',
  UnfreezeColumns: 'UnfreezeColumns',
  RenameSheet: 'RenameSheet',
  DeleteSheet: 'DeleteSheet',
  DuplicateSheet: 'DuplicateSheet',
  HideSheet: 'HideSheet',
  ShowSheet: 'ShowSheet',
  MoveSheet: 'MoveSheet',
  MoveSheetInDirection: 'MoveSheetInDirection',
  ChangeTabColor: 'ChangeTabColor',
  Undo: 'Undo',
  Redo: 'Redo',
  ClearFormatting: 'ClearFormatting',
  SetFormat: 'SetFormat',
  Delete: 'Delete',
  Cut: 'Cut',
  Copy: 'Copy',
  Paste: 'Paste',
  PasteValue: 'PasteValue',
  PasteFormatting: 'PasteFormatting',
  PasteTransposed: 'PasteTransposed',
  PasteFormula: 'PasteFormula',
  PasteLink: 'PasteLink',
  SetBorder: 'SetBorder',
  DecreaseDecimalPlaces: 'DecreaseDecimalPlaces',
  IncreaseDecimalPlaces: 'IncreaseDecimalPlaces',
  MergeAll: 'MergeAll',
  MergeHorizontally: 'MergeHorizontally',
  MergeVertically: 'MergeVertically',
  Unmerge: 'Unmerge',
  SavePaintFormat: 'SavePaintFormat',
  InsertCellsShiftRight: 'InsertCellsShiftRight',
  InsertCellsShiftDown: 'InsertCellsShiftDown',
  InsertRowsAbove: 'InsertRowsAbove',
  InsertRowsBelow: 'InsertRowsBelow',
  InsertColumnsLeft: 'InsertColumnsLeft',
  InsertColumnsRight: 'InsertColumnsRight',
  CreateNewSheet: 'CreateNewSheet',
  CreateChart: 'CreateChart',
  UpdateChart: 'UpdateChart',
  SortColumnAscending: 'SortColumnAscending',
  SortColumnDescending: 'SortColumnDescending',
  ToggleFilter: 'ToggleFilter',
  ProtectRange: 'ProtectRange',
  UnprotectRange: 'UnprotectRange',
  RequestDataValidation: 'RequestDataValidation',
  InitialLoadComplete: 'InitialLoadComplete',
} as const

export type SheetsActionType = (typeof SheetsActions)[keyof typeof SheetsActions]
