export const CONTACT_ERROR = {
    TYPE3_CONTACT_VERIFICATION: 3,
    TYPE3_CONTACT_DECRYPTION: 2,
    TYPE2_CONTACT_VERIFICATION: 1,
    TYPE1_CONTACT: 0
};

export const HTTP_ERROR_CODES = {
    ABORTED: -1,
    TIMEOUT: 0,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429
};

export const API_CUSTOM_ERROR_CODES = {
    APP_VERSION_BAD: 5003,

    API_VERSION_INVALID: 5004,
    API_VERSION_BAD: 5005,
    API_OFFLINE: 7001,

    PASSWORD_WRONG: 8002,

    HUMAN_VERIFICATION_REQUIRED: 9001,

    AUTH_AUTH_ACCOUNT_DISABLED: 10003,
    AUTH_REFRESH_TOKEN_INVALID: 10013,
    AUTH_COOKIES_REFRESH_INVALID: 10021,

    USER_CREATE_TOKEN_INVALID: 12087,

    MESSAGE_VALIDATE_KEY_ID_NOT_ASSOCIATED: 15213,
    EVENTS_ID_INVALID: 18001,

    PAYMENTS_PAYPAL_CONNECTION_EXCEPTION: 22802,

    FILTER_CREATE_TOO_MANY_ACTIVE: 50016,

    MESSAGE_SEARCH_QUERY_SYNTAX: 15225,
    MESSAGE_UPDATE_DRAFT_NOT_EXIST: 15033,
    MESSAGE_UPDATE_DRAFT_NOT_DRAFT: 15034,

    KEY_GET_INPUT_INVALID: 33101,
    KEY_GET_ADDRESS_MISSING: 33102,
    KEY_GET_DOMAIN_MISSING_MX: 33103,
    INCOMING_DEFAULT_UPDATE_NOT_EXIST: 35023
};

export const EVENT_ERRORS = {
    MAIL: 1,
    CONTACTS: 2
};
