module.exports = {
    extends: ['stylelint-config-prettier'],
    rules: {
        'color-no-invalid-hex': true,
        'font-family-no-duplicate-names': true,
        'font-family-no-missing-generic-family-keyword': true,
        'function-calc-no-invalid': true,
        'function-calc-no-unspaced-operator': true,
        'function-linear-gradient-no-nonstandard-direction': true,
        'string-no-newline': true,
        'unit-no-unknown': true,
        'property-no-unknown': true,
        'keyframe-declaration-no-important': true,
        'declaration-block-no-duplicate-properties': [
            true,
            { ignore: ['consecutive-duplicates-with-different-values'] },
        ],
        'declaration-block-no-shorthand-property-overrides': true,
        'block-no-empty': true,
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-element-no-unknown': true,
        'selector-type-no-unknown': true,
        'media-feature-name-no-unknown': true,
        'at-rule-no-unknown': [
            true,
            {
                ignoreAtRules: [
                    'use',
                    'forward',
                    'import',
                    'mixin',
                    'include',
                    'function',
                    'extend',
                    'at-root',
                    'error',
                    'warn',
                    'debug',
                    'if',
                    'else',
                    'each',
                    'for',
                    'while',
                    'return',
                ],
            },
        ],
        'comment-no-empty': true,
        'no-descending-specificity': null,
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'no-extra-semicolons': true,
        'no-invalid-double-slash-comments': null,

        'alpha-value-notation': 'number',
        'hue-degree-notation': 'angle',
        'color-function-notation': 'modern',
        'color-named': ['always-where-possible', { ignore: ['inside-function'] }],
        'color-no-hex': null,
        'font-weight-notation': 'named-where-possible',
        'function-url-no-scheme-relative': null,
        'keyframes-name-pattern': null,
        'number-max-precision': 3,
        'time-min-milliseconds': null,
        'shorthand-property-no-redundant-values': true,
        'value-no-vendor-prefix': true,
        'custom-property-pattern': null,
        'property-no-vendor-prefix': true,
        'selector-pseudo-element-colon-notation': 'double',

        'function-name-case': 'lower',
        'function-url-quotes': 'never',
    },
};
