import React from 'react';
import PropTypes from 'prop-types';
import { c } from 'ttag';

const getCountry = (abbreviation) => {
    const abbr = abbreviation === 'UK' ? 'GB' : abbreviation;
    return {
        AF: c('Country').t`Afghanistan`,
        AL: c('Country').t`Albania`,
        DZ: c('Country').t`Algeria`,
        AD: c('Country').t`Andorra`,
        AO: c('Country').t`Angola`,
        AI: c('Country').t`Anguilla`,
        AG: c('Country').t`Antigua and Barbuda`,
        AR: c('Country').t`Argentina`,
        AM: c('Country').t`Armenia`,
        AW: c('Country').t`Aruba`,
        AU: c('Country').t`Australia`,
        AT: c('Country').t`Austria`,
        AZ: c('Country').t`Azerbaijan`,
        BS: c('Country').t`Bahamas`,
        BH: c('Country').t`Bahrain`,
        BD: c('Country').t`Bangladesh`,
        BB: c('Country').t`Barbados`,
        BY: c('Country').t`Belarus`,
        BE: c('Country').t`Belgium`,
        BZ: c('Country').t`Belize`,
        BJ: c('Country').t`Benin`,
        BM: c('Country').t`Bermuda`,
        BT: c('Country').t`Bhutan`,
        BO: c('Country').t`Bolivia`,
        BA: c('Country').t`Bosnia Herzegovina`,
        BW: c('Country').t`Botswana`,
        BV: c('Country').t`Bouvet Island`,
        BR: c('Country').t`Brazil`,
        IO: c('Country').t`British Indian Ocean Territory`,
        VG: c('Country').t`British Virgin Islands`,
        BN: c('Country').t`Brunei Darussalam`,
        BG: c('Country').t`Bulgaria`,
        BF: c('Country').t`Burkina Faso`,
        BI: c('Country').t`Burundi`,
        KH: c('Country').t`Cambodia`,
        CM: c('Country').t`Cameroon`,
        CA: c('Country').t`Canada`,
        CV: c('Country').t`Cape Verde`,
        KY: c('Country').t`Cayman Islands`,
        CF: c('Country').t`Central African Republic`,
        TD: c('Country').t`Chad`,
        CL: c('Country').t`Chile`,
        CN: c('Country').t`China`,
        CX: c('Country').t`Christmas Island`,
        CC: c('Country').t`Cocos (Keeling) Islands`,
        CO: c('Country').t`Colombia`,
        KM: c('Country').t`Comoros`,
        CG: c('Country').t`Congo`,
        CD: c('Country').t`Congo (The Democratic Republic of the)`,
        CK: c('Country').t`Cook Islands`,
        CR: c('Country').t`Costa Rica`,
        CI: c('Country').t`Cote d Ivoire (Ivory Coast)`,
        HR: c('Country').t`Croatia`,
        CU: c('Country').t`Cuba`,
        CW: c('Country').t`Curaçao`,
        CY: c('Country').t`Cyprus`,
        CZ: c('Country').t`Czech Republic`,
        DK: c('Country').t`Denmark`,
        DJ: c('Country').t`Djibouti`,
        DM: c('Country').t`Dominica`,
        DO: c('Country').t`Dominican Republic`,
        TL: c('Country').t`East Timor`,
        EC: c('Country').t`Ecuador`,
        EG: c('Country').t`Egypt`,
        SV: c('Country').t`El Salvador`,
        GQ: c('Country').t`Equatorial Guinea`,
        ER: c('Country').t`Eritrea`,
        EE: c('Country').t`Estonia`,
        ET: c('Country').t`Ethiopia`,
        FK: c('Country').t`Falkland Islands (Malvinas)`,
        FO: c('Country').t`Faroe Islands`,
        FJ: c('Country').t`Fiji`,
        FI: c('Country').t`Finland`,
        FR: c('Country').t`France`,
        GF: c('Country').t`French Guiana`,
        PF: c('Country').t`French Polynesia`,
        TF: c('Country').t`French Southern Territories`,
        GA: c('Country').t`Gabon`,
        GM: c('Country').t`Gambia`,
        GE: c('Country').t`Georgia`,
        DE: c('Country').t`Germany`,
        GH: c('Country').t`Ghana`,
        GI: c('Country').t`Gibraltar`,
        GR: c('Country').t`Greece`,
        GL: c('Country').t`Greenland`,
        GD: c('Country').t`Grenada`,
        GP: c('Country').t`Guadeloupe`,
        GT: c('Country').t`Guatemala`,
        GN: c('Country').t`Guinea`,
        GW: c('Country').t`Guinea-Bissau`,
        GY: c('Country').t`Guyana`,
        HT: c('Country').t`Haiti`,
        HM: c('Country').t`Heard Island and McDonald Islands`,
        VA: c('Country').t`Holy See (Vatican City State)`,
        HN: c('Country').t`Honduras`,
        HK: c('Country').t`Hong Kong`,
        HU: c('Country').t`Hungary`,
        IS: c('Country').t`Iceland`,
        IN: c('Country').t`India`,
        ID: c('Country').t`Indonesia`,
        IQ: c('Country').t`Iraq`,
        IE: c('Country').t`Ireland`,
        IR: c('Country').t`Islamic Republic of Iran`,
        IL: c('Country').t`Israel`,
        IT: c('Country').t`Italy`,
        JM: c('Country').t`Jamaica`,
        JP: c('Country').t`Japan`,
        JO: c('Country').t`Jordan`,
        KZ: c('Country').t`Kazakhstan`,
        KE: c('Country').t`Kenya`,
        KI: c('Country').t`Kiribati`,
        KP: c('Country').t`Korea (Democratic People s Republic of)`,
        KR: c('Country').t`Korea (Republic of)`,
        KW: c('Country').t`Kuwait`,
        KG: c('Country').t`Kyrgzstan`,
        LA: c('Country').t`Lao People s Democratic Republic`,
        LV: c('Country').t`Latvia`,
        LB: c('Country').t`Lebanon`,
        LS: c('Country').t`Lesotho`,
        LR: c('Country').t`Liberia`,
        LY: c('Country').t`Libyan Arab Jamahiriya`,
        LI: c('Country').t`Liechtenstein`,
        LT: c('Country').t`Lithuania`,
        LU: c('Country').t`Luxembourg`,
        MO: c('Country').t`Macao`,
        MK: c('Country').t`Macedonia`,
        MG: c('Country').t`Madagascar`,
        MW: c('Country').t`Malawi`,
        MY: c('Country').t`Malaysia`,
        MV: c('Country').t`Maldives`,
        ML: c('Country').t`Mali`,
        MT: c('Country').t`Malta`,
        MH: c('Country').t`Marshall Islands`,
        MQ: c('Country').t`Martinique`,
        MR: c('Country').t`Mauritania`,
        MU: c('Country').t`Mauritius`,
        YT: c('Country').t`Mayotte`,
        MX: c('Country').t`Mexico`,
        MD: c('Country').t`Moldova`,
        MC: c('Country').t`Monaco`,
        MN: c('Country').t`Mongolia`,
        ME: c('Country').t`Montenegro`,
        MS: c('Country').t`Montserrat`,
        MA: c('Country').t`Morocco`,
        MZ: c('Country').t`Mozambique`,
        MM: c('Country').t`Myanmar`,
        NA: c('Country').t`Namibia`,
        NR: c('Country').t`Nauru`,
        NP: c('Country').t`Nepal`,
        NL: c('Country').t`Netherlands`,
        AN: c('Country').t`Netherlands Antilles`,
        NC: c('Country').t`New Caledonia`,
        NZ: c('Country').t`New Zealand`,
        NI: c('Country').t`Nicaragua`,
        NE: c('Country').t`Niger`,
        NG: c('Country').t`Nigeria`,
        NU: c('Country').t`Niue`,
        NF: c('Country').t`Norfolk Island`,
        NO: c('Country').t`Norway`,
        OM: c('Country').t`Oman`,
        PK: c('Country').t`Pakistan`,
        PW: c('Country').t`Palau`,
        PA: c('Country').t`Panama`,
        PG: c('Country').t`Papua New Guinea`,
        PY: c('Country').t`Paraguay`,
        PE: c('Country').t`Peru`,
        PH: c('Country').t`Philippines`,
        PN: c('Country').t`Pitcairn`,
        PL: c('Country').t`Poland`,
        PT: c('Country').t`Portugal`,
        QA: c('Country').t`Qatar`,
        RE: c('Country').t`Reunion`,
        RO: c('Country').t`Romania`,
        RU: c('Country').t`Russian Federation`,
        RW: c('Country').t`Rwanda`,
        SH: c('Country').t`Saint Helena`,
        KN: c('Country').t`Saint Kitts and Nevis`,
        LC: c('Country').t`Saint Lucia`,
        PM: c('Country').t`Saint Pierre and Miquelon`,
        VC: c('Country').t`Saint Vincent and the Grenadines`,
        WS: c('Country').t`Samoa`,
        SM: c('Country').t`San Marino`,
        ST: c('Country').t`Sao Tome and Principe`,
        SA: c('Country').t`Saudi Arabia`,
        SN: c('Country').t`Senegal`,
        RS: c('Country').t`Serbia`,
        SC: c('Country').t`Seychelles`,
        SL: c('Country').t`Sierra Leone`,
        SG: c('Country').t`Singapore`,
        SK: c('Country').t`Slovakia`,
        SI: c('Country').t`Slovenia`,
        SB: c('Country').t`Solomon Islands`,
        SO: c('Country').t`Somalia`,
        ZA: c('Country').t`South Africa`,
        GS: c('Country').t`South Georgia and the South Sandwich Islands`,
        ES: c('Country').t`Spain`,
        LK: c('Country').t`Sri Lanka`,
        SD: c('Country').t`Sudan`,
        SR: c('Country').t`Suriname`,
        SJ: c('Country').t`Svalbard and Jan Mayen`,
        SZ: c('Country').t`Swaziland`,
        SE: c('Country').t`Sweden`,
        CH: c('Country').t`Switzerland`,
        SY: c('Country').t`Syrian Arab Republic`,
        TW: c('Country').t`Taiwan`,
        TJ: c('Country').t`Tajikstan`,
        TZ: c('Country').t`Tanzania United Republic`,
        TH: c('Country').t`Thailand`,
        TG: c('Country').t`Togo`,
        TK: c('Country').t`Tokelau`,
        TO: c('Country').t`Tonga`,
        TT: c('Country').t`Trinidad and Tobago`,
        TN: c('Country').t`Tunisia`,
        TR: c('Country').t`Turkey`,
        TM: c('Country').t`Turkmenistan`,
        TC: c('Country').t`Turks and Caicos Islands`,
        TV: c('Country').t`Tuvalu`,
        UG: c('Country').t`Uganda`,
        UA: c('Country').t`Ukraine`,
        AE: c('Country').t`United Arab Emirates`,
        GB: c('Country').t`United Kingdom`,
        US: c('Country').t`United States`,
        UY: c('Country').t`Uruguay`,
        UZ: c('Country').t`Uzbekistan`,
        VU: c('Country').t`Vanuatu`,
        VE: c('Country').t`Venezuela`,
        VN: c('Country').t`Vietnam`,
        WF: c('Country').t`Wallis and Futuna`,
        EH: c('Country').t`Western Sahara`,
        YE: c('Country').t`Yemen`,
        ZM: c('Country').t`Zambia`,
        ZW: c('Country').t`Zimbabwe`
    }[abbr];
};

const Country = ({ entry, exit }) => {
    return (
        <div className="inline-flex-vcenter">
            <img src="" alt={`flag-${exit}`} />
            {getCountry(exit)}
            {entry && entry !== exit && <span className="ml0-25 opacity-50">(via {getCountry(entry)})</span>}
        </div>
    );
};

Country.propTypes = {
    entry: PropTypes.string,
    exit: PropTypes.string.isRequired
};

export default Country;
