// Multi-language stopwords - common words that don't help with search relevance
// Covers: English, German, French, Spanish, Italian, Portuguese, Dutch
// Acquired largely from https://github.com/Alir3z4/stop-words
export const STOPWORDS = new Set([
    // ═══════════════════════════════════════════════════════════════════════════
    // ENGLISH
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'the', 'and', 'for', 'are', 'but', 'not', 'you', 'all',
    'this', 'that', 'these', 'those', 'some', 'any', 'each',
    'every', 'both', 'few', 'more', 'most', 'other', 'such',
    // Pronouns
    'can', 'her', 'him', 'his', 'she', 'its', 'our', 'out',
    'they', 'them', 'their', 'there', 'here', 'who', 'whom',
    'whose', 'which', 'what', 'whoever', 'whatever', 'myself',
    'yourself', 'himself', 'herself', 'itself', 'ourselves',
    'themselves', 'someone', 'anyone', 'everyone', 'nobody',
    'somebody', 'anybody', 'everybody', 'something', 'anything',
    'everything', 'nothing',
    // Common verbs
    'was', 'were', 'been', 'has', 'had', 'have', 'having',
    'will', 'would', 'could', 'should', 'shall', 'may', 'might',
    'must', 'need', 'want', 'like', 'does', 'did', 'done',
    'being', 'get', 'got', 'getting', 'gets',
    'make', 'made', 'making', 'makes',
    'take', 'took', 'taken', 'taking', 'takes',
    'come', 'came', 'coming', 'comes',
    'give', 'gave', 'given', 'giving', 'gives',
    'know', 'knew', 'known', 'knowing', 'knows',
    'think', 'thought', 'thinking', 'thinks',
    'see', 'saw', 'seen', 'seeing', 'sees',
    'use', 'used', 'using', 'uses',
    'find', 'found', 'finding', 'finds',
    'tell', 'told', 'telling', 'tells',
    'ask', 'asked', 'asking', 'asks',
    'work', 'worked', 'working', 'works',
    'try', 'tried', 'trying', 'tries',
    'call', 'called', 'calling', 'calls',
    'keep', 'kept', 'keeping', 'keeps',
    'let', 'lets', 'letting',
    'put', 'puts', 'putting',
    'say', 'said', 'saying', 'says',
    'seem', 'seemed', 'seems', 'seeming',
    'leave', 'left', 'leaving', 'leaves',
    'feel', 'felt', 'feeling', 'feels',
    'become', 'became', 'becomes', 'becoming',
    'begin', 'began', 'begun', 'begins', 'beginning',
    'show', 'showed', 'shown', 'showing', 'shows',
    'run', 'ran', 'running', 'runs',
    'move', 'moved', 'moving', 'moves',
    'look', 'looked', 'looking', 'looks',
    'going', 'went', 'goes', 'gone',
    'bring', 'brought', 'bringing', 'brings',
    'hold', 'held', 'holding', 'holds',
    'turn', 'turned', 'turning', 'turns',
    'start', 'started', 'starting', 'starts',
    'help', 'helped', 'helping', 'helps',
    'play', 'played', 'playing', 'plays',
    'set', 'sets', 'setting',
    'add', 'added', 'adding', 'adds',
    'change', 'changed', 'changing', 'changes',
    'follow', 'followed', 'following', 'follows',
    'stop', 'stopped', 'stopping', 'stops',
    'open', 'opened', 'opening', 'opens',
    'close', 'closed', 'closing', 'closes',
    'read', 'reading', 'reads',
    'write', 'wrote', 'written', 'writing', 'writes',
    'learn', 'learned', 'learning', 'learns',
    'grow', 'grew', 'grown', 'growing', 'grows',
    'lead', 'led', 'leading', 'leads',
    'live', 'lived', 'living', 'lives',
    'stand', 'stood', 'standing', 'stands',
    'hear', 'heard', 'hearing', 'hears',
    'allow', 'allowed', 'allowing', 'allows',
    'spend', 'spent', 'spending', 'spends',
    'meet', 'met', 'meeting', 'meets',
    'include', 'included', 'including', 'includes',
    'continue', 'continued', 'continuing', 'continues',
    'happen', 'happened', 'happening', 'happens',
    'provide', 'provided', 'providing', 'provides',
    'sit', 'sat', 'sitting', 'sits',
    'create', 'created', 'creating', 'creates',
    'offer', 'offered', 'offering', 'offers',
    'consider', 'considered', 'considering', 'considers',
    'appear', 'appeared', 'appearing', 'appears',
    'wait', 'waited', 'waiting', 'waits',
    'serve', 'served', 'serving', 'serves',
    'expect', 'expected', 'expecting', 'expects',
    'stay', 'stayed', 'staying', 'stays',
    'remain', 'remained', 'remaining', 'remains',
    'suggest', 'suggested', 'suggesting', 'suggests',
    'require', 'required', 'requiring', 'requires',
    'report', 'reported', 'reporting', 'reports',
    'decide', 'decided', 'deciding', 'decides',
    'mean', 'meant', 'meaning', 'means',
    // Question words
    'when', 'where', 'how', 'why',
    // Prepositions & conjunctions
    'with', 'from', 'into', 'over', 'after', 'before',
    'about', 'against', 'between', 'through', 'during',
    'without', 'under', 'within', 'along', 'among',
    'around', 'behind', 'below', 'beside', 'besides',
    'beyond', 'upon', 'toward', 'towards', 'across',
    'because', 'since', 'while', 'although', 'though',
    'unless', 'until', 'whether', 'either', 'neither',
    'nor', 'yet', 'once',
    // Common adverbs
    'then', 'than', 'also', 'just', 'only', 'very',
    'same', 'well', 'even', 'back', 'still', 'too',
    'much', 'really', 'already', 'always', 'never',
    'often', 'ever', 'quite', 'probably', 'perhaps',
    'maybe', 'certainly', 'actually', 'finally', 'simply',
    'quickly', 'easily', 'clearly', 'exactly', 'likely',
    'especially', 'usually', 'generally', 'however',
    'therefore', 'thus', 'indeed', 'rather', 'pretty',
    'almost', 'enough', 'now', 'later', 'soon',
    'again', 'further', 'together', 'away', 'else',
    // Common adjectives
    'good', 'new', 'first', 'last', 'long', 'great',
    'little', 'own', 'old', 'right', 'big', 'high',
    'different', 'small', 'large', 'next', 'early',
    'young', 'important', 'public', 'bad', 'better',
    'best', 'sure', 'free', 'able', 'real', 'full',
    'late', 'hard', 'major', 'certain', 'kind', 'sort',
    'whole', 'possible', 'particular', 'available',
    'special', 'true', 'necessary', 'recent', 'nice',
    'easy', 'ready', 'simple', 'clear', 'due',
    // Common nouns
    'one', 'two', 'way', 'ways', 'thing', 'things',
    'time', 'times', 'year', 'years', 'day', 'days',
    'today', 'part', 'parts', 'place', 'places',
    'case', 'cases', 'week', 'weeks', 'point', 'points',
    'fact', 'facts', 'number', 'numbers', 'world',
    'group', 'groups', 'problem', 'problems', 'hand',
    'hands', 'life', 'people', 'man', 'men', 'woman',
    'women', 'child', 'children', 'lot', 'lots',
    'example', 'examples', 'end', 'ends', 'home',
    'area', 'areas', 'side', 'sides', 'line', 'lines',
    'bit', 'bits', 'matter', 'matters', 'question',
    'questions', 'issue', 'issues', 'reason', 'reasons',
    'result', 'results', 'level', 'levels', 'order',
    'kind', 'kinds', 'head', 'name', 'names',

    // ═══════════════════════════════════════════════════════════════════════════
    // GERMAN (Deutsch)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'der', 'die', 'das', 'den', 'dem', 'des', 'ein', 'eine',
    'einer', 'einem', 'einen', 'eines', 'kein', 'keine',
    'keiner', 'keinem', 'keinen', 'keines',
    // Pronouns
    'ich', 'mir', 'mich', 'mein', 'meine', 'meiner', 'meinem', 'meinen',
    'dich', 'dir', 'dein', 'deine', 'deiner', 'deinem', 'deinen',
    'ihn', 'ihm', 'ihr', 'ihre', 'ihrer', 'ihrem', 'ihren', 'ihres',
    'wir', 'uns', 'unser', 'unsere', 'unserer', 'unserem', 'unseren',
    'sie', 'sich', 'euch', 'euer', 'eure', 'eurer', 'eurem', 'euren',
    'man', 'wer', 'was', 'welche', 'welcher', 'welches', 'welchem', 'welchen',
    'jemand', 'niemand', 'etwas', 'nichts', 'alles', 'alle', 'aller',
    'dieser', 'diese', 'dieses', 'diesem', 'diesen',
    'jener', 'jene', 'jenes', 'jenem', 'jenen',
    // Common verbs
    'sein', 'ist', 'sind', 'war', 'waren', 'gewesen', 'bin', 'bist',
    'haben', 'hat', 'hatte', 'hatten', 'gehabt', 'habe', 'hast',
    'werden', 'wird', 'wurde', 'wurden', 'geworden', 'werde', 'wirst',
    'können', 'kann', 'konnte', 'konnten', 'gekonnt', 'kannst',
    'müssen', 'muss', 'musste', 'mussten', 'gemusst', 'musst',
    'sollen', 'soll', 'sollte', 'sollten', 'gesollt', 'sollst',
    'wollen', 'will', 'wollte', 'wollten', 'gewollt', 'willst',
    'dürfen', 'darf', 'durfte', 'durften', 'gedurft', 'darfst',
    'mögen', 'mag', 'mochte', 'mochten', 'gemocht', 'magst',
    'machen', 'macht', 'machte', 'gemacht', 'mache', 'machst',
    'gehen', 'geht', 'ging', 'gegangen', 'gehe', 'gehst',
    'kommen', 'kommt', 'kam', 'gekommen', 'komme', 'kommst',
    'sehen', 'sieht', 'sah', 'gesehen', 'sehe', 'siehst',
    'geben', 'gibt', 'gab', 'gegeben', 'gebe', 'gibst',
    'nehmen', 'nimmt', 'nahm', 'genommen', 'nehme', 'nimmst',
    'finden', 'findet', 'fand', 'gefunden', 'finde', 'findest',
    'sagen', 'sagt', 'sagte', 'gesagt', 'sage', 'sagst',
    'wissen', 'weiß', 'weiss', 'wusste', 'gewusst', 'weißt', 'weisst',
    'lassen', 'lässt', 'laesst', 'ließ', 'liess', 'gelassen',
    'stehen', 'steht', 'stand', 'gestanden', 'stehe', 'stehst',
    'bleiben', 'bleibt', 'blieb', 'geblieben', 'bleibe', 'bleibst',
    // Question words
    'wann', 'warum', 'weshalb', 'wieso', 'woher', 'wohin', 'womit',
    // Prepositions & conjunctions
    'mit', 'bei', 'nach', 'von', 'aus', 'für', 'über', 'unter',
    'vor', 'hinter', 'neben', 'zwischen', 'durch', 'gegen', 'ohne',
    'bis', 'seit', 'während', 'wegen', 'trotz', 'außer', 'ausser',
    'und', 'oder', 'aber', 'denn', 'weil', 'dass', 'wenn', 'als',
    'ob', 'obwohl', 'damit', 'bevor', 'nachdem', 'sobald', 'solange',
    // Common adverbs
    'auch', 'noch', 'schon', 'nur', 'sehr', 'immer', 'wieder',
    'dann', 'dort', 'hier', 'heute', 'gestern', 'morgen', 'jetzt',
    'nun', 'gerade', 'gleich', 'bald', 'oft', 'manchmal', 'nie',
    'vielleicht', 'wahrscheinlich', 'sicher', 'bestimmt', 'genau',
    'eigentlich', 'überhaupt', 'ueberhaupt', 'ziemlich', 'fast',
    'etwa', 'ungefähr', 'ungefaehr', 'ganz', 'gar', 'sogar',
    // Common adjectives
    'gut', 'neu', 'alt', 'groß', 'gross', 'klein', 'lang', 'kurz',
    'hoch', 'tief', 'breit', 'schmal', 'dick', 'dünn', 'duenn',
    'schnell', 'langsam', 'früh', 'frueh', 'spät', 'spaet',
    'erste', 'ersten', 'erster', 'erstes', 'letzte', 'letzten', 'letzter',
    'nächste', 'naechste', 'vorige', 'andere', 'anderen', 'anderer',
    'gleiche', 'gleichen', 'gleicher', 'selbe', 'selben', 'selber',
    'ganze', 'ganzen', 'ganzer', 'ganzes', 'viel', 'viele', 'vielen',
    'wenig', 'wenige', 'wenigen', 'mehr', 'weniger', 'meiste', 'meisten',
    // Common nouns
    'zeit', 'jahr', 'jahre', 'jahren', 'tag', 'tage', 'tagen',
    'woche', 'wochen', 'monat', 'monate', 'monaten',
    'weise', 'art', 'fall', 'fälle', 'faelle', 'teil', 'teile', 'teilen',
    'seite', 'seiten', 'stelle', 'stellen', 'punkt', 'punkte', 'punkten',
    'frage', 'fragen', 'antwort', 'antworten', 'grund', 'gründe', 'gruende',

    // ═══════════════════════════════════════════════════════════════════════════
    // FRENCH (Français)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'les', 'une', 'des', 'aux', 'ces', 'cet', 'cette',
    'mon', 'ton', 'son', 'mes', 'tes', 'ses', 'notre', 'votre', 'leur',
    'nos', 'vos', 'leurs', 'tout', 'tous', 'toute', 'toutes',
    'quel', 'quelle', 'quels', 'quelles', 'chaque', 'plusieurs',
    'aucun', 'aucune', 'certain', 'certains', 'certaine', 'certaines',
    // Pronouns
    'moi', 'toi', 'lui', 'elle', 'nous', 'vous', 'eux', 'elles',
    'celui', 'celle', 'ceux', 'celles', 'ceci', 'cela',
    'qui', 'que', 'quoi', 'dont', 'lequel', 'laquelle', 'lesquels', 'lesquelles',
    'quelqu', 'quelque', 'quelques', 'personne', 'rien', 'chacun', 'chacune',
    // Common verbs
    'être', 'etre', 'suis', 'est', 'sommes', 'sont', 'êtes', 'etes',
    'étais', 'etais', 'était', 'etait', 'étions', 'etions', 'étiez', 'etiez', 'étaient', 'etaient',
    'été', 'ete', 'serai', 'sera', 'serons', 'serez', 'seront',
    'avoir', 'avons', 'avez', 'ont', 'avais', 'avait', 'avions', 'aviez', 'avaient',
    'aurai', 'aura', 'aurons', 'aurez', 'auront',
    'faire', 'fais', 'fait', 'faisons', 'faites', 'font', 'faisais', 'faisait',
    'aller', 'vais', 'vas', 'allons', 'allez', 'vont', 'allais', 'allait',
    'pouvoir', 'peux', 'peut', 'pouvons', 'pouvez', 'peuvent', 'pouvais',
    'vouloir', 'veux', 'veut', 'voulons', 'voulez', 'veulent', 'voulais',
    'devoir', 'dois', 'doit', 'devons', 'devez', 'doivent', 'devais',
    'savoir', 'sais', 'sait', 'savons', 'savez', 'savent', 'savais',
    'voir', 'vois', 'voit', 'voyons', 'voyez', 'voient', 'voyais',
    'venir', 'viens', 'vient', 'venons', 'venez', 'viennent', 'venais',
    'prendre', 'prends', 'prend', 'prenons', 'prenez', 'prennent', 'prenais',
    'dire', 'dis', 'dit', 'disons', 'dites', 'disent', 'disais',
    'mettre', 'mets', 'met', 'mettons', 'mettez', 'mettent', 'mettais',
    'donner', 'donne', 'donnes', 'donnons', 'donnez', 'donnent', 'donnais',
    'passer', 'passe', 'passes', 'passons', 'passez', 'passent', 'passais',
    'trouver', 'trouve', 'trouves', 'trouvons', 'trouvez', 'trouvent',
    'parler', 'parle', 'parles', 'parlons', 'parlez', 'parlent',
    'croire', 'crois', 'croit', 'croyons', 'croyez', 'croient',
    'sembler', 'semble', 'sembles', 'semblons', 'semblez', 'semblent',
    // Question words
    'quand', 'comment', 'pourquoi', 'combien',
    // Prepositions & conjunctions
    'dans', 'sur', 'sous', 'avec', 'sans', 'pour', 'par', 'chez',
    'entre', 'vers', 'avant', 'après', 'apres', 'depuis', 'pendant',
    'contre', 'selon', 'malgré', 'malgre', 'sauf', 'hormis',
    'mais', 'donc', 'car', 'parce', 'puisque', 'comme', 'lorsque',
    'quand', 'quoique', 'afin', 'tandis', 'sinon',
    // Common adverbs
    'pas', 'plus', 'moins', 'très', 'tres', 'bien', 'mal', 'peu',
    'beaucoup', 'trop', 'assez', 'aussi', 'encore', 'toujours', 'jamais',
    'souvent', 'parfois', 'déjà', 'deja', 'bientôt', 'bientot',
    'maintenant', 'ici', 'ailleurs', 'partout', 'vraiment',
    'peut-être', 'peut', 'seulement', 'surtout', 'plutôt', 'plutot',
    // Common adjectives
    'bon', 'bonne', 'bons', 'bonnes', 'mauvais', 'mauvaise',
    'grand', 'grande', 'grands', 'grandes', 'petit', 'petite', 'petits', 'petites',
    'nouveau', 'nouvelle', 'nouveaux', 'nouvelles', 'vieux', 'vieille',
    'jeune', 'jeunes', 'premier', 'première', 'premiere', 'dernier', 'dernière', 'derniere',
    'autre', 'autres', 'même', 'meme', 'mêmes', 'memes', 'seul', 'seule', 'seuls', 'seules',
    'propre', 'propres', 'long', 'longue', 'longs', 'longues',
    // Common nouns
    'fois', 'chose', 'choses', 'temps', 'jour', 'jours', 'nuit', 'nuits',
    'semaine', 'semaines', 'mois', 'année', 'annee', 'années', 'annees',
    'heure', 'heures', 'minute', 'minutes', 'moment', 'moments',
    'manière', 'maniere', 'façon', 'facon', 'sorte', 'sortes',
    'partie', 'parties', 'côté', 'cote', 'côtés', 'cotes',
    'homme', 'hommes', 'femme', 'femmes', 'enfant', 'enfants',
    'gens', 'monde', 'vie', 'vies', 'main', 'mains',

    // ═══════════════════════════════════════════════════════════════════════════
    // SPANISH (Español)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'las', 'los', 'una', 'uno', 'unas', 'unos', 'esto', 'esta',
    'estos', 'estas', 'ese', 'esa', 'esos', 'esas', 'aquel', 'aquella',
    'aquellos', 'aquellas', 'algo', 'nada', 'nadie', 'algún', 'algun',
    'alguna', 'algunos', 'algunas', 'ningún', 'ningun', 'ninguna',
    'cada', 'todo', 'toda', 'todos', 'todas', 'otro', 'otra', 'otros', 'otras',
    // Pronouns
    'conmigo', 'contigo', 'consigo', 'nosotros', 'nosotras',
    'vosotros', 'vosotras', 'ellos', 'ellas', 'usted', 'ustedes',
    'quien', 'quienes', 'cual', 'cuales', 'cuyo', 'cuya', 'cuyos', 'cuyas',
    'alguien', 'cualquier', 'cualquiera', 'quienquiera',
    // Common verbs
    'ser', 'soy', 'eres', 'somos', 'sois', 'era', 'eras', 'éramos', 'eramos',
    'eran', 'fui', 'fue', 'fuimos', 'fueron', 'sido', 'siendo',
    'estar', 'estoy', 'estás', 'estas', 'está', 'esta', 'estamos', 'estáis', 'estais',
    'están', 'estan', 'estaba', 'estuve', 'estuvo', 'estado', 'estando',
    'haber', 'hay', 'hemos', 'han', 'había', 'habia', 'hubo', 'habido',
    'tener', 'tengo', 'tienes', 'tiene', 'tenemos', 'tenéis', 'teneis', 'tienen',
    'tenía', 'tenia', 'tuvo', 'tenido', 'teniendo',
    'hacer', 'hago', 'haces', 'hace', 'hacemos', 'hacéis', 'haceis', 'hacen',
    'hacía', 'hacia', 'hizo', 'hecho', 'haciendo',
    'poder', 'puedo', 'puedes', 'puede', 'podemos', 'podéis', 'podeis', 'pueden',
    'podía', 'podia', 'pudo', 'podido', 'pudiendo',
    'querer', 'quiero', 'quieres', 'quiere', 'queremos', 'queréis', 'quereis', 'quieren',
    'quería', 'queria', 'quiso', 'querido', 'queriendo',
    'deber', 'debo', 'debes', 'debe', 'debemos', 'debéis', 'debeis', 'deben',
    'debía', 'debia', 'debió', 'debio', 'debido', 'debiendo',
    'saber', 'sabemos', 'sabéis', 'sabeis', 'saben', 'sabía', 'sabia', 'supo', 'sabido',
    'decir', 'digo', 'dices', 'dice', 'decimos', 'decís', 'decis', 'dicen',
    'decía', 'decia', 'dijo', 'dicho', 'diciendo',
    'dar', 'doy', 'das', 'damos', 'dais', 'dan', 'daba', 'dio', 'dado', 'dando',
    'ver', 'veo', 'ves', 'vemos', 'veis', 'ven', 'veía', 'veia', 'vio', 'visto', 'viendo',
    'llegar', 'llego', 'llegas', 'llega', 'llegamos', 'llegan', 'llegó', 'llego', 'llegado',
    'pasar', 'paso', 'pasas', 'pasa', 'pasamos', 'pasan', 'pasó', 'pasado',
    'quedar', 'quedo', 'quedas', 'queda', 'quedamos', 'quedan', 'quedó', 'quedado',
    'creer', 'creo', 'crees', 'cree', 'creemos', 'creen', 'creía', 'creia', 'creyó', 'creido',
    'parecer', 'parece', 'parecen', 'parecía', 'parecia', 'pareció', 'parecio',
    // Question words
    'cuándo', 'cuando', 'dónde', 'donde', 'cómo', 'como', 'qué', 'que', 'por qué', 'porque',
    'cuánto', 'cuanto', 'cuánta', 'cuanta', 'cuántos', 'cuantos', 'cuántas', 'cuantas',
    // Prepositions & conjunctions
    'con', 'sin', 'sobre', 'bajo', 'entre', 'hacia', 'hasta', 'desde',
    'durante', 'mediante', 'según', 'segun', 'contra', 'tras',
    'pero', 'sino', 'aunque', 'porque', 'pues', 'mientras', 'además', 'ademas',
    // Common adverbs
    'más', 'mas', 'menos', 'muy', 'tan', 'tanto', 'tanta', 'tantos', 'tantas',
    'bien', 'mal', 'mejor', 'peor', 'siempre', 'nunca', 'también', 'tambien',
    'tampoco', 'ahora', 'aquí', 'aqui', 'allí', 'alli', 'hoy', 'ayer', 'mañana', 'manana',
    'pronto', 'tarde', 'temprano', 'todavía', 'todavia', 'quizás', 'quizas', 'acaso',
    'sólo', 'solo', 'solamente', 'apenas', 'casi', 'bastante', 'demasiado',
    // Common adjectives
    'bueno', 'buena', 'buenos', 'buenas', 'malo', 'mala', 'malos', 'malas',
    'grande', 'grandes', 'pequeño', 'pequeno', 'pequeña', 'pequena',
    'nuevo', 'nueva', 'nuevos', 'nuevas', 'viejo', 'vieja', 'viejos', 'viejas',
    'primero', 'primera', 'último', 'ultimo', 'última', 'ultima',
    'mismo', 'misma', 'mismos', 'mismas', 'propio', 'propia', 'propios', 'propias',
    // Common nouns
    'vez', 'veces', 'cosa', 'cosas', 'tiempo', 'tiempos', 'día', 'dia', 'días', 'dias',
    'año', 'anos', 'años', 'semana', 'semanas', 'mes', 'meses',
    'hora', 'horas', 'momento', 'momentos', 'manera', 'maneras', 'forma', 'formas',
    'parte', 'partes', 'lado', 'lados', 'lugar', 'lugares',
    'hombre', 'hombres', 'mujer', 'mujeres', 'niño', 'nino', 'niños', 'ninos',
    'gente', 'persona', 'personas', 'vida', 'vidas', 'mano', 'manos',

    // ═══════════════════════════════════════════════════════════════════════════
    // ITALIAN (Italiano)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'gli', 'uno', 'una', 'dello', 'della', 'dei', 'degli', 'delle',
    'questo', 'questa', 'questi', 'queste', 'quello', 'quella', 'quelli', 'quelle',
    'qualche', 'qualcuno', 'qualcosa', 'niente', 'nulla', 'nessuno', 'nessuna',
    'ogni', 'tutto', 'tutta', 'tutti', 'tutte', 'altro', 'altra', 'altri', 'altre',
    // Pronouns
    'egli', 'essa', 'esso', 'esse', 'essi', 'noi', 'voi', 'loro',
    'chi', 'che', 'cui', 'quale', 'quali', 'quanto', 'quanta', 'quanti', 'quante',
    'ciò', 'cio', 'stesso', 'stessa', 'stessi', 'stesse',
    // Common verbs
    'essere', 'sono', 'sei', 'siamo', 'siete', 'erano', 'ero', 'era', 'eravamo',
    'stato', 'stata', 'stati', 'state', 'sarà', 'sara', 'saremo', 'saranno',
    'avere', 'abbiamo', 'avete', 'hanno', 'avevo', 'aveva', 'avevamo',
    'avuto', 'avrà', 'avra', 'avremo', 'avranno',
    'fare', 'faccio', 'fai', 'facciamo', 'fate', 'fanno', 'facevo', 'faceva',
    'fatto', 'farà', 'fara', 'faremo', 'faranno',
    'potere', 'posso', 'puoi', 'può', 'puo', 'possiamo', 'potete', 'possono',
    'potevo', 'poteva', 'potuto', 'potrà', 'potra',
    'volere', 'voglio', 'vuoi', 'vuole', 'vogliamo', 'volete', 'vogliono',
    'volevo', 'voleva', 'voluto', 'vorrà', 'vorra',
    'dovere', 'devo', 'devi', 'deve', 'dobbiamo', 'dovete', 'devono',
    'dovevo', 'doveva', 'dovuto', 'dovrà', 'dovra',
    'sapere', 'sappiamo', 'sapete', 'sanno', 'sapevo', 'sapeva', 'saputo',
    'dire', 'dico', 'dici', 'dice', 'diciamo', 'dite', 'dicono', 'dicevo', 'detto',
    'dare', 'diamo', 'date', 'danno', 'davo', 'dava', 'dato',
    'vedere', 'vedo', 'vedi', 'vede', 'vediamo', 'vedete', 'vedono', 'vedevo', 'visto',
    'venire', 'vengo', 'vieni', 'viene', 'veniamo', 'venite', 'vengono', 'venivo', 'venuto',
    'andare', 'vado', 'vai', 'andiamo', 'andate', 'vanno', 'andavo', 'andato',
    'stare', 'sto', 'stai', 'sta', 'stiamo', 'stanno', 'stavo', 'stato',
    'trovare', 'trovo', 'trovi', 'trova', 'troviamo', 'trovano', 'trovato',
    'pensare', 'penso', 'pensi', 'pensa', 'pensiamo', 'pensano', 'pensato',
    'sembrare', 'sembra', 'sembrano', 'sembrava', 'sembrato',
    // Question words
    'quando', 'dove', 'come', 'perché', 'perche',
    // Prepositions & conjunctions
    'con', 'senza', 'sopra', 'sotto', 'tra', 'fra', 'verso', 'fino',
    'durante', 'secondo', 'contro', 'dopo', 'prima',
    'mentre', 'perché', 'perche', 'poiché', 'poiche', 'quindi', 'però', 'pero',
    'oppure', 'anche', 'ancora', 'già', 'gia', 'mai', 'sempre', 'spesso',
    // Common adverbs
    'più', 'piu', 'meno', 'molto', 'molta', 'molti', 'molte', 'poco', 'poca', 'pochi', 'poche',
    'troppo', 'troppa', 'troppi', 'troppe', 'tanto', 'tanta', 'tanti', 'tante',
    'bene', 'male', 'meglio', 'peggio', 'ora', 'adesso', 'qui', 'qua',
    'oggi', 'ieri', 'domani', 'presto', 'tardi', 'subito', 'quasi', 'forse',
    'solo', 'soltanto', 'soprattutto', 'davvero', 'veramente', 'proprio',
    // Common adjectives
    'buono', 'buona', 'buoni', 'buone', 'cattivo', 'cattiva',
    'grande', 'grandi', 'piccolo', 'piccola', 'piccoli', 'piccole',
    'nuovo', 'nuova', 'nuovi', 'nuove', 'vecchio', 'vecchia', 'vecchi', 'vecchie',
    'primo', 'prima', 'primi', 'prime', 'ultimo', 'ultima', 'ultimi', 'ultime',
    // Common nouns
    'volta', 'volte', 'cosa', 'cose', 'tempo', 'tempi', 'giorno', 'giorni',
    'anno', 'anni', 'settimana', 'settimane', 'mese', 'mesi',
    'ora', 'ore', 'momento', 'momenti', 'modo', 'modi', 'maniera', 'maniere',
    'parte', 'parti', 'lato', 'lati', 'posto', 'posti', 'luogo', 'luoghi',
    'uomo', 'uomini', 'donna', 'donne', 'bambino', 'bambini',
    'gente', 'persona', 'persone', 'vita', 'vite',

    // ═══════════════════════════════════════════════════════════════════════════
    // PORTUGUESE (Português)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'uma', 'umas', 'uns', 'aos', 'das', 'dos', 'nas', 'nos', 'pela', 'pelo',
    'pelas', 'pelos', 'esta', 'este', 'estas', 'estes', 'essa', 'esse', 'essas', 'esses',
    'aquela', 'aquele', 'aquelas', 'aqueles', 'aquilo', 'isto', 'isso',
    'algum', 'alguma', 'alguns', 'algumas', 'nenhum', 'nenhuma',
    'tudo', 'toda', 'todos', 'todas', 'cada', 'qualquer',
    'outro', 'outra', 'outros', 'outras', 'muito', 'muita', 'muitos', 'muitas',
    'pouco', 'pouca', 'poucos', 'poucas',
    // Pronouns
    'ele', 'ela', 'eles', 'elas', 'nós', 'nos', 'vós', 'vos', 'vocês', 'voces',
    'quem', 'qual', 'quais', 'cujo', 'cuja', 'cujos', 'cujas',
    'alguém', 'alguem', 'ninguém', 'ninguem', 'algo', 'nada',
    'mesmo', 'mesma', 'mesmos', 'mesmas', 'próprio', 'proprio', 'própria', 'propria',
    // Common verbs
    'ser', 'sou', 'somos', 'são', 'sao', 'era', 'eram', 'foi', 'foram', 'sido', 'sendo',
    'estar', 'estou', 'está', 'esta', 'estamos', 'estão', 'estao', 'estava', 'estavam',
    'estive', 'esteve', 'estiveram', 'estado', 'estando',
    'ter', 'tenho', 'tem', 'temos', 'têm', 'tem', 'tinha', 'tinham', 'teve', 'tiveram', 'tido',
    'haver', 'há', 'ha', 'havia', 'houve', 'havido',
    'fazer', 'faço', 'faco', 'faz', 'fazemos', 'fazem', 'fazia', 'fez', 'fizeram', 'feito',
    'poder', 'posso', 'pode', 'podemos', 'podem', 'podia', 'pôde', 'pode', 'puderam', 'podido',
    'querer', 'quero', 'quer', 'queremos', 'querem', 'queria', 'quis', 'quiseram', 'querido',
    'dever', 'devo', 'deve', 'devemos', 'devem', 'devia', 'deveu', 'devido',
    'saber', 'sei', 'sabe', 'sabemos', 'sabem', 'sabia', 'soube', 'souberam', 'sabido',
    'dizer', 'digo', 'diz', 'dizemos', 'dizem', 'dizia', 'disse', 'disseram', 'dito',
    'dar', 'dou', 'dá', 'da', 'damos', 'dão', 'dao', 'dava', 'deu', 'deram', 'dado',
    'ver', 'vejo', 'vê', 've', 'vemos', 'veem', 'vêem', 'via', 'viu', 'viram', 'visto',
    'vir', 'venho', 'vem', 'vimos', 'vêm', 'vem', 'vinha', 'veio', 'vieram', 'vindo',
    'ficar', 'fico', 'fica', 'ficamos', 'ficam', 'ficava', 'ficou', 'ficaram', 'ficado',
    'parecer', 'parece', 'parecem', 'parecia', 'pareceu', 'parecido',
    // Question words
    'quando', 'onde', 'como', 'porque', 'por que', 'quanto', 'quanta', 'quantos', 'quantas',
    // Prepositions & conjunctions
    'com', 'sem', 'sobre', 'sob', 'entre', 'para', 'por', 'até', 'ate', 'desde',
    'durante', 'contra', 'após', 'apos', 'antes', 'depois',
    'mas', 'porém', 'porem', 'contudo', 'todavia', 'entretanto',
    'porque', 'pois', 'portanto', 'logo', 'assim', 'então', 'entao',
    'enquanto', 'embora', 'apesar', 'ainda', 'também', 'tambem',
    // Common adverbs
    'mais', 'menos', 'bem', 'mal', 'melhor', 'pior', 'sempre', 'nunca',
    'agora', 'aqui', 'ali', 'hoje', 'ontem', 'amanhã', 'amanha',
    'logo', 'cedo', 'tarde', 'talvez', 'quase', 'apenas', 'somente',
    'bastante', 'demais', 'tão', 'tao', 'tanta', 'tantas', 'tantos',
    // Common adjectives
    'bom', 'boa', 'bons', 'boas', 'mau', 'ruim',
    'grande', 'grandes', 'pequeno', 'pequena', 'pequenos', 'pequenas',
    'novo', 'nova', 'novos', 'novas', 'velho', 'velha', 'velhos', 'velhas',
    'primeiro', 'primeira', 'últimos', 'ultimos', 'últimas', 'ultimas',
    // Common nouns
    'vez', 'vezes', 'coisa', 'coisas', 'tempo', 'tempos', 'dia', 'dias',
    'ano', 'anos', 'semana', 'semanas', 'mês', 'mes', 'meses',
    'hora', 'horas', 'momento', 'momentos', 'modo', 'modos', 'forma', 'formas',
    'parte', 'partes', 'lado', 'lados', 'lugar', 'lugares',
    'homem', 'homens', 'mulher', 'mulheres', 'criança', 'crianca', 'crianças', 'criancas',
    'gente', 'pessoa', 'pessoas', 'vida', 'vidas',

    // ═══════════════════════════════════════════════════════════════════════════
    // DUTCH (Nederlands)
    // ═══════════════════════════════════════════════════════════════════════════
    // Articles & determiners
    'het', 'een', 'deze', 'dit', 'die', 'dat', 'welke', 'welk',
    'geen', 'alle', 'beide', 'elk', 'elke', 'ieder', 'iedere',
    'veel', 'vele', 'weinig', 'weinige', 'meer', 'meest', 'meeste',
    'ander', 'andere', 'anderen', 'zelf', 'eigen',
    // Pronouns
    'ik', 'mij', 'jij', 'jou', 'hij', 'zij', 'het', 'wij', 'ons', 'jullie', 'hen', 'hun',
    'wie', 'wat', 'waar', 'iemand', 'niemand', 'iets', 'niets',
    'men', 'zich', 'elkaar', 'mijn', 'jouw', 'zijn', 'haar', 'onze', 'uw',
    // Common verbs
    'zijn', 'ben', 'bent', 'was', 'waren', 'geweest', 'zal', 'zult', 'zullen', 'zou', 'zouden',
    'hebben', 'heb', 'hebt', 'heeft', 'hadden', 'gehad',
    'worden', 'word', 'wordt', 'werd', 'werden', 'geworden',
    'kunnen', 'kun', 'kunt', 'kon', 'konden', 'gekund',
    'moeten', 'moet', 'moest', 'moesten', 'gemoeten',
    'willen', 'wil', 'wilt', 'wilde', 'wilden', 'gewild',
    'mogen', 'mag', 'mocht', 'mochten', 'gemogen',
    'zullen', 'zou', 'zouden',
    'gaan', 'ga', 'gaat', 'ging', 'gingen', 'gegaan',
    'komen', 'kom', 'komt', 'kwam', 'kwamen', 'gekomen',
    'doen', 'doe', 'doet', 'deed', 'deden', 'gedaan',
    'zien', 'zie', 'ziet', 'zag', 'zagen', 'gezien',
    'maken', 'maak', 'maakt', 'maakte', 'maakten', 'gemaakt',
    'geven', 'geef', 'geeft', 'gaf', 'gaven', 'gegeven',
    'nemen', 'neem', 'neemt', 'nam', 'namen', 'genomen',
    'weten', 'weet', 'wist', 'wisten', 'geweten',
    'zeggen', 'zeg', 'zegt', 'zei', 'zeiden', 'gezegd',
    'denken', 'denk', 'denkt', 'dacht', 'dachten', 'gedacht',
    'vinden', 'vind', 'vindt', 'vond', 'vonden', 'gevonden',
    'staan', 'sta', 'staat', 'stond', 'stonden', 'gestaan',
    'blijven', 'blijf', 'blijft', 'bleef', 'bleven', 'gebleven',
    'laten', 'laat', 'liet', 'lieten', 'gelaten',
    'lijken', 'lijk', 'lijkt', 'leek', 'leken', 'geleken',
    // Question words
    'wanneer', 'waarom', 'hoe', 'hoeveel',
    // Prepositions & conjunctions
    'met', 'bij', 'naar', 'van', 'uit', 'voor', 'over', 'onder',
    'door', 'tegen', 'zonder', 'tot', 'sinds', 'tijdens', 'tussen',
    'achter', 'naast', 'boven', 'beneden', 'binnen', 'buiten',
    'maar', 'want', 'omdat', 'hoewel', 'terwijl', 'zodra', 'voordat', 'nadat',
    'als', 'indien', 'tenzij', 'mits', 'ofschoon', 'alhoewel',
    // Common adverbs
    'ook', 'nog', 'al', 'alleen', 'altijd', 'nooit', 'vaak', 'soms',
    'nu', 'dan', 'hier', 'daar', 'vandaag', 'gisteren', 'morgen',
    'vroeg', 'laat', 'gauw', 'snel', 'langzaam', 'goed', 'slecht',
    'heel', 'erg', 'nogal', 'vrij', 'tamelijk', 'redelijk', 'best',
    'misschien', 'waarschijnlijk', 'zeker', 'beslist', 'vast',
    'eigenlijk', 'immers', 'trouwens', 'overigens', 'namelijk',
    // Common adjectives
    'goed', 'goede', 'nieuw', 'nieuwe', 'oud', 'oude', 'groot', 'grote',
    'klein', 'kleine', 'lang', 'lange', 'kort', 'korte',
    'hoog', 'hoge', 'laag', 'lage', 'breed', 'brede', 'smal', 'smalle',
    'eerste', 'laatste', 'volgende', 'vorige', 'zelfde',
    // Common nouns
    'keer', 'ding', 'dingen', 'tijd', 'dag', 'dagen', 'week', 'weken',
    'maand', 'maanden', 'jaar', 'jaren', 'uur', 'uren',
    'plaats', 'plaatsen', 'kant', 'kanten', 'deel', 'delen',
    'vraag', 'vragen', 'punt', 'punten', 'zaak', 'zaken',
    'mens', 'mensen', 'vrouw', 'vrouwen', 'kind', 'kinderen',
    'leven', 'wereld', 'hand', 'handen',
]);